displayName=Dopamine Simulator
author=Zoinkwiz
description=A progression system layered over the progression system layered over the game
tags=cards,collection,progression,packs,meta,tcg
plugins=com.dopaminesimulator.DopamineSimulatorPlugin
version=0.1.0
build=standard
