displayName=Dopamine Simulator
author=Zoinkwiz
description=Collect cards and buy upgrades as you play
tags=cards,collection,progression,packs,meta,tcg,idle
plugins=com.dopaminesimulator.DopamineSimulatorPlugin
version=0.3.0
build=standard
