/*
 * Copyright (c) 2026, Zoinkwiz <https://github.com/Zoinkwiz>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package com.dopaminesimulator.cards.sets;

import com.dopaminesimulator.cards.Card;
import com.dopaminesimulator.cards.CardGroup;
import com.dopaminesimulator.cards.CardSet;
import com.dopaminesimulator.cards.Rarity;
import net.runelite.api.gameval.ItemID;
import net.runelite.api.gameval.SpriteID;

public enum ConstructionCards implements CardGroup
{
	CRUDE_WOODEN_CHAIR("Crude wooden chair", Rarity.COMMON, ItemID.POH_ARMCHAIR_1, -1),
	EXIT_PORTAL("Exit portal", Rarity.COMMON, ItemID.POH_GARDEN_CENTREPIECE_1, -1),
	GARDEN("Garden", Rarity.COMMON, ItemID.POH_GARDEN_CENTREPIECE_3, -1),
	LOW_LEVEL_PLANT("Low-level plant", Rarity.COMMON, ItemID.POH_GUIDE_PLANT_1, -1),
	MAHOGANY_HOMES_BEGINNER("Mahogany Homes (beginner)", Rarity.COMMON, ItemID.CUP_OF_TEA, -1),
	PARLOUR("Parlour", Rarity.COMMON, ItemID.POH_ARMCHAIR_7, -1),
	BROWN_RUG("Brown rug", Rarity.COMMON, ItemID.POH_RUG_1, -1),
	TORN_CURTAINS("Torn curtains", Rarity.COMMON, ItemID.POH_CURTAINS_1, -1),
	CLAY_FIREPLACE("Clay fireplace", Rarity.COMMON, ItemID.POH_FIREPLACE_1, -1),
	WOODEN_BOOKCASE("Wooden bookcase", Rarity.COMMON, ItemID.POH_BOOKCASE_1, -1),
	CAT_BLANKET("Cat blanket", Rarity.COMMON, ItemID.POH_CAT_BASKET_1, -1),
	DECORATIVE_ROCK("Decorative rock", Rarity.COMMON, ItemID.POH_GARDEN_CENTREPIECE_2, -1),
	FIREPIT("Firepit", Rarity.COMMON, ItemID.POH_STOVE_1, -1),
	KITCHEN("Kitchen", Rarity.COMMON, ItemID.POH_STOVE_7, -1),
	TREE("Tree", Rarity.COMMON, ItemID.POH_TREE_1, -1),
	MID_LEVEL_PLANTS("Mid-level plants", Rarity.COMMON, ItemID.POH_GUIDE_PLANT_2, -1),
	WOODEN_SHELVES_1("Wooden shelves 1", Rarity.COMMON, ItemID.POH_KITCHEN_SHELVES_1, -1),
	BEER_BARREL("Beer barrel", Rarity.COMMON, ItemID.POH_BARREL_1, -1),
	PUMP_AND_DRAIN("Pump and drain", Rarity.COMMON, ItemID.POH_SINK_1, -1),
	WOODEN_CHAIR("Wooden chair", Rarity.COMMON, ItemID.POH_ARMCHAIR_2, -1),
	WOODEN_LARDER("Wooden larder", Rarity.COMMON, ItemID.POH_LARDER_1, -1),
	CRAB_TRAPS("Crab traps", Rarity.COMMON, ItemID.RED_CRAB, -1),
	DINING_ROOM("Dining room", Rarity.COMMON, ItemID.POH_DINING_TABLE_7, -1),
	NICE_TREE("Nice tree", Rarity.COMMON, ItemID.POH_TREE_2, -1),
	POND("Pond", Rarity.COMMON, ItemID.POH_GARDEN_CENTREPIECE_3, -1),
	WOODEN_DINING_BENCH("Wooden dining bench", Rarity.COMMON, ItemID.POH_DINING_CHAIRS_1, -1),
	WOODEN_DINING_TABLE("Wooden dining table", Rarity.COMMON, ItemID.POH_DINING_TABLE_1, -1),
	FIREPIT_WITH_HOOK("Firepit with hook", Rarity.COMMON, ItemID.POH_STOVE_2, -1),
	CIDER_BARREL("Cider barrel", Rarity.COMMON, ItemID.POH_BARREL_2, -1),
	HIGH_LEVEL_PLANTS("High-level plants", Rarity.COMMON, ItemID.POH_GUIDE_PLANT_3, -1),
	STASH_UNITS_BEGINNER("STASH units (beginner)", Rarity.COMMON, ItemID.HH_DUMMY_HIDEYHOLE_BEGINNER, -1),
	WOODEN_KITCHEN_TABLE("Wooden kitchen table", Rarity.COMMON, ItemID.POH_KITCHENTABLE_1, -1),
	WOODEN_SHELVES_2("Wooden shelves 2", Rarity.COMMON, ItemID.POH_KITCHEN_SHELVES_2, -1),
	RUG("Rug", Rarity.COMMON, ItemID.POH_RUG_2, -1),
	ROCKING_CHAIR("Rocking chair", Rarity.COMMON, ItemID.POH_ARMCHAIR_3, -1),
	IMP_STATUE("Imp statue", Rarity.COMMON, ItemID.POH_GARDEN_CENTREPIECE_4, -1),
	OAK_TREE("Oak tree", Rarity.COMMON, ItemID.POH_TREE_3, -1),
	REPAIR_BENCH("Repair bench", Rarity.COMMON, ItemID.POH_REPAIR_BENCH_1, -1),
	TOOL_STORE_1("Tool store 1", Rarity.COMMON, ItemID.POH_TOOL_STORE_1, -1),
	WORKSHOP("Workshop", Rarity.COMMON, ItemID.POH_WORKBENCH_5, -1),
	CRAFTING_TABLE_1("Crafting table 1", Rarity.COMMON, ItemID.POH_CRAFTING_TABLE_1, -1),
	OAK_WALL_DECORATION("Oak wall decoration", Rarity.COMMON, ItemID.POH_WALL_CREST_1, -1),
	PLUMING_STAND("Pluming stand", Rarity.COMMON, ItemID.POH_HERALDRY_BENCH_1, -1),
	FIREPIT_WITH_POT("Firepit with pot", Rarity.COMMON, ItemID.POH_STOVE_3, -1),
	WATER_PUMP("Water pump", Rarity.COMMON, ItemID.PATTERN_SACK_EMPTY_DUMMY, -1),
	WOODEN_WORKBENCH("Wooden workbench", Rarity.COMMON, ItemID.POH_WORKBENCH_1, -1),
	ASGARNIAN_ALE_BARREL("Asgarnian Ale barrel", Rarity.COMMON, ItemID.POH_BARREL_3, -1),
	CURTAINS("Curtains", Rarity.COMMON, ItemID.POH_CURTAINS_2, -1),
	CAT_BASKET("Cat basket", Rarity.COMMON, ItemID.POH_CAT_BASKET_2, -1),
	COOKING_POT("Cooking pot", Rarity.COMMON, ItemID.PATTERN_BASKET_EMPTY_DUMMY, -1),
	OAK_CHAIR("Oak chair", Rarity.COMMON, ItemID.POH_ARMCHAIR_4, -1),
	BEDROOM("Bedroom", Rarity.UNCOMMON, ItemID.POH_BED_7, -1),
	MAHOGANY_HOMES_NOVICE("Mahogany Homes (novice)", Rarity.UNCOMMON, ItemID.POH_CLAYCUP_TEA, -1),
	RICK("Rick", Rarity.UNCOMMON, ItemID.GRAIL_BELL, -1),
	SHOE_BOX("Shoe box", Rarity.UNCOMMON, ItemID.POH_WARDROBE_1, -1),
	WOODEN_BED("Wooden bed", Rarity.UNCOMMON, ItemID.POH_BED_1, -1),
	WOODEN_SHAVING_STAND("Wooden shaving stand", Rarity.UNCOMMON, ItemID.POH_MIRROR_1, -1),
	OAK_DINING_BENCH("Oak dining bench", Rarity.UNCOMMON, ItemID.POH_DINING_CHAIRS_2, -1),
	OAK_DINING_TABLE("Oak dining table", Rarity.UNCOMMON, ItemID.POH_DINING_TABLE_2, -1),
	WOODEN_SHELVES_3("Wooden shelves 3", Rarity.UNCOMMON, ItemID.POH_KITCHEN_SHELVES_3, -1),
	POTTERY_WHEEL("Pottery wheel", Rarity.UNCOMMON, ItemID.PATTERN_STRAWBERRY_DUMMY, -1),
	SMALL_OVEN("Small oven", Rarity.UNCOMMON, ItemID.POH_STOVE_4, -1),
	SPINNING_WHEEL("Spinning wheel", Rarity.UNCOMMON, ItemID.PATTERN_ONION_SEED_4_DUMMY, -1),
	CRAFTING_TABLE_2("Crafting table 2", Rarity.UNCOMMON, ItemID.POH_CRAFTING_TABLE_2, -1),
	HALL_SKILL_TROPHIES("Hall (skill trophies)", Rarity.UNCOMMON, ItemID.POH_STAIRS_MARBLE, -1),
	MAID("Maid", Rarity.UNCOMMON, ItemID.GRAIL_BELL, -1),
	OAK_CLOCK("Oak clock", Rarity.UNCOMMON, ItemID.POH_CLOCK_1, -1),
	TOOL_STORE_2("Tool store 2", Rarity.UNCOMMON, ItemID.POH_TOOL_STORE_2, -1),
	GREENMAN_S_ALE_BARREL("Greenman's Ale barrel", Rarity.UNCOMMON, ItemID.POH_BARREL_4, -1),
	OAK_ARMCHAIR("Oak armchair", Rarity.UNCOMMON, ItemID.POH_ARMCHAIR_5, -1),
	ROPE_BELL_PULL("Rope bell pull", Rarity.UNCOMMON, ItemID.POH_BELLPULL_1, -1),
	LEAGUE_HALL("League hall", Rarity.UNCOMMON, ItemID.POH_LEAGUEHALL_TROPHY_PEDESTAL_SIMPLE, -1),
	OAK_CHEST_OF_DRAWERS("Oak chest of drawers", Rarity.UNCOMMON, ItemID.POH_WARDROBE_2, -1),
	OAK_STAIRCASE("Oak staircase", Rarity.UNCOMMON, ItemID.POH_STAIRS_OAK, -1),
	PUMP_AND_TUB("Pump and tub", Rarity.UNCOMMON, ItemID.POH_SINK_2, -1),
	STASH_UNITS_EASY("STASH units (easy)", Rarity.UNCOMMON, ItemID.HH_DUMMY_HIDEYHOLE_EASY, -1),
	TROPHY_PEDESTAL("Trophy pedestal", Rarity.UNCOMMON, ItemID.POH_LEAGUEHALL_TROPHY_PEDESTAL_SIMPLE, -1),
	DEADMAN_RUG("Deadman rug", Rarity.UNCOMMON, ItemID.POH_RUG_DEADMAN, -1),
	RUG_LEAGUE_HALL("Rug (League hall)", Rarity.UNCOMMON, ItemID.POH_LEAGUEHALL_RUG_SIMPLE, -1),
	SUIT_OF_ARMOUR("Suit of Armour", Rarity.UNCOMMON, ItemID.POH_GUIDE_ARMOUR, -1),
	TRAILBLAZER_RUG("Trailblazer rug", Rarity.UNCOMMON, ItemID.POH_LEAGUEHALL_RUG_TRAILBLAZER, -1),
	LARGE_OVEN("Large oven", Rarity.UNCOMMON, ItemID.POH_STOVE_5, -1),
	OAK_BOOKCASE("Oak bookcase", Rarity.UNCOMMON, ItemID.POH_BOOKCASE_2, -1),
	OAK_SHAVING_STAND("Oak shaving stand", Rarity.UNCOMMON, ItemID.POH_MIRROR_2, -1),
	BANNER_STAND("Banner stand", Rarity.UNCOMMON, ItemID.POH_LEAGUEHALL_BANNERSTAND_SIMPLE, -1),
	CHAMBERS_OF_XERIC_SMALL_STORAGE_UNIT("Chambers of Xeric - Small storage unit", Rarity.UNCOMMON, ItemID.RAIDS_STORAGE_1, -1),
	COOK("Cook", Rarity.UNCOMMON, ItemID.GRAIL_BELL, -1),
	GAMES_ROOM("Games room", Rarity.UNCOMMON, ItemID.POH_RANGING_GAME_2, -1),
	HOOP_AND_STICK_GAME("Hoop-and-stick game", Rarity.UNCOMMON, ItemID.POH_RANGING_GAME_1, -1),
	OAK_BED("Oak bed", Rarity.UNCOMMON, ItemID.POH_BED_2, -1),
	REPAIR_PISCARILIUS_FISHING_CRANES("Repair Piscarilius fishing cranes", Rarity.UNCOMMON, ItemID.HAMMER, -1),
	WILLOW_TREE("Willow tree", Rarity.UNCOMMON, ItemID.POH_TREE_4, -1),
	CARVED_OAK_DINING_BENCH("Carved oak dining bench", Rarity.UNCOMMON, ItemID.POH_DINING_CHAIRS_3, -1),
	CARVED_OAK_DINING_TABLE("Carved oak dining table", Rarity.UNCOMMON, ItemID.POH_DINING_TABLE_3, -1),
	LOOM("Loom", Rarity.UNCOMMON, ItemID.PATTERN_REDBERRY_DUMMY, -1),
	BOXING_RING("Boxing ring", Rarity.UNCOMMON, ItemID.POH_COMBAT_RING_1, -1),
	COMBAT_ROOM("Combat room", Rarity.UNCOMMON, ItemID.POH_COMBAT_RING_5, -1),
	LEAGUE_STATUE("League statue", Rarity.UNCOMMON, ItemID.POH_LEAGUEHALL_STATUE_SIMPLE, -1),
	OAK_KITCHEN_TABLE("Oak kitchen table", Rarity.UNCOMMON, ItemID.POH_KITCHENTABLE_2, -1),
	OAK_WORKBENCH("Oak workbench", Rarity.UNCOMMON, ItemID.POH_WORKBENCH_2, -1),
	TRAILBLAZER_GLOBE("Trailblazer globe", Rarity.UNCOMMON, ItemID.POH_LEAGUEHALL_STATUE_TRAILBLAZER, -1),
	CUSHIONED_CAT_BASKET("Cushioned cat basket", Rarity.UNCOMMON, ItemID.POH_CAT_BASKET_3, -1),
	OAK_LARDER("Oak larder", Rarity.UNCOMMON, ItemID.POH_LARDER_2, -1),
	STONE_FIREPLACE("Stone fireplace", Rarity.UNCOMMON, ItemID.POH_FIREPLACE_2, -1),
	BOXING_GLOVE_RACK("Boxing glove rack", Rarity.UNCOMMON, ItemID.POH_WEAPON_RACK_1, -1),
	CRAFTING_TABLE_3("Crafting table 3", Rarity.UNCOMMON, ItemID.POH_CRAFTING_TABLE_3, -1),
	LARGE_OAK_BED("Large oak bed", Rarity.UNCOMMON, ItemID.POH_BED_3, -1),
	OAK_OUTFIT_STAND("Oak outfit stand", Rarity.UNCOMMON, ItemID.POH_LEAGUEHALL_OUTFITSTAND_OAK, -1),
	OAK_PRIZE_CHEST("Oak prize chest", Rarity.UNCOMMON, ItemID.POH_PRIZE_CHEST_1, -1),
	OAK_SHELVES_1("Oak shelves 1", Rarity.UNCOMMON, ItemID.POH_KITCHEN_SHELVES_4, -1),
	STEEL_RANGE("Steel range", Rarity.UNCOMMON, ItemID.POH_STOVE_6, -1),
	FIRE_OF_ETERNAL_LIGHT("Fire of Eternal Light", Rarity.UNCOMMON, ItemID.MY2ARM_DUMMY_FIRE_LIGHT, -1),
	FIRE_OF_NOURISHMENT("Fire of Nourishment", Rarity.UNCOMMON, ItemID.MY2ARM_DUMMY_FIRE_HERB, -1),
	HALL_QUEST_TROPHIES("Hall (quest trophies)", Rarity.UNCOMMON, ItemID.POH_SPIRALSTAIRS_MARBLE, -1),
	SMALL_PORTRAIT("Small portrait", Rarity.UNCOMMON, ItemID.POH_GUIDE_PORTRAIT1, -1),
	TEAK_ARMCHAIR("Teak armchair", Rarity.UNCOMMON, ItemID.POH_ARMCHAIR_6, -1),
	TOOL_STORE_3("Tool store 3", Rarity.UNCOMMON, ItemID.POH_TOOL_STORE_3, -1),
	WHETSTONE("Whetstone", Rarity.UNCOMMON, ItemID.POH_REPAIR_BENCH_2, -1),
	DRAGON_BITTER_BARREL("Dragon Bitter barrel", Rarity.UNCOMMON, ItemID.POH_BARREL_5, -1),
	OAK_MOUNTED_FISH_DISPLAY("Oak mounted fish display", Rarity.UNCOMMON, ItemID.PATTERN_BASS_DUMMY, -1),
	OAK_TROPHY_CASE("Oak trophy case", Rarity.UNCOMMON, ItemID.POH_LEAGUEHALL_TROPHYCASE_OAK, -1),
	TEAK_WALL_DECORATION("Teak wall decoration", Rarity.UNCOMMON, ItemID.POH_WALL_CREST_2, -1),
	GRASSLAND_PET_HABITAT("Grassland pet habitat", Rarity.UNCOMMON, ItemID.POH_MENAGERIE_HABITAT_1, -1),
	LESSER_MAGICAL_BALANCE("Lesser magical balance", Rarity.UNCOMMON, ItemID.POH_ELEMENTAL_BALANCE_1, -1),
	MENAGERIE("Menagerie", Rarity.UNCOMMON, ItemID.POH_MENAGERIE_PETHOUSE_3, -1),
	OAK_DRESSER("Oak dresser", Rarity.UNCOMMON, ItemID.POH_MIRROR_3, -1),
	OAK_PET_FEEDER("Oak pet feeder", Rarity.UNCOMMON, ItemID.POH_MENAGERIE_PETFEEDER_1, -1),
	OAK_PET_HOUSE_3_PETS("Oak pet house (3 pets)", Rarity.UNCOMMON, ItemID.POH_MENAGERIE_PETHOUSE_1, -1),
	POTTERY_OVEN("Pottery oven", Rarity.UNCOMMON, ItemID.PATTERN_TINDERBOX_DUMMY, -1),
	TEAK_BELL_PULL("Teak bell pull", Rarity.UNCOMMON, ItemID.POH_BELLPULL_2, -1),
	PET_LIST_FOR_ONE_OFF_PETS("Pet list (for one-off pets)", Rarity.UNCOMMON, ItemID.POH_MENAGERIE_PETLIST_1, -1),
	SMALL_MAP("Small map", Rarity.UNCOMMON, ItemID.POH_MAP_1, -1),
	TEAK_DINING_BENCH("Teak dining bench", Rarity.UNCOMMON, ItemID.POH_DINING_CHAIRS_4, -1),
	TEAK_DINING_TABLE("Teak dining table", Rarity.UNCOMMON, ItemID.POH_DINING_TABLE_4, -1),
	TEAK_MOUNTED_HEAD_DISPLAY("Teak mounted head display", Rarity.UNCOMMON, ItemID.POH_GUIDE_HEAD1, -1),
	CLAY_ATTACK_STONE("Clay attack stone", Rarity.UNCOMMON, ItemID.POH_ATTACK_STONE_1, -1),
	JESTER_GAME("Jester game", Rarity.UNCOMMON, ItemID.POH_PARTY_GAME_1, -1),
	OAK_PET_SCRATCHING_POST("Oak pet scratching post", Rarity.UNCOMMON, ItemID.POH_MENAGERIE_SCRATCHINGPOST_1, -1),
	OAK_WARDROBE_BEDROOM("Oak wardrobe (bedroom)", Rarity.UNCOMMON, ItemID.POH_WARDROBE_3, -1),
	BUTLER("Butler", Rarity.RARE, ItemID.GRAIL_BELL, -1),
	MAHOGANY_BOOKCASE("Mahogany bookcase", Rarity.RARE, ItemID.POH_BOOKCASE_3, -1),
	OAK_LECTERN("Oak lectern", Rarity.RARE, ItemID.POH_LECTERN_1, -1),
	OPULENT_CURTAINS("Opulent curtains", Rarity.RARE, ItemID.POH_CURTAINS_3, -1),
	S_T_A_S_H_CHART("S.T.A.S.H chart", Rarity.RARE, ItemID.POH_WALLCHART_4, -1),
	STUDY("Study", Rarity.RARE, ItemID.POH_LECTERN_7, -1),
	TEAK_BED("Teak bed", Rarity.RARE, ItemID.POH_BED_4, -1),
	TIP_JAR("Tip jar", Rarity.RARE, ItemID.POH_TIPJAR, -1),
	FENCING_RING("Fencing ring", Rarity.RARE, ItemID.POH_COMBAT_RING_2, -1),
	GLOBE("Globe", Rarity.RARE, ItemID.POH_GLOBE_1, -1),
	RUNE_DISPLAY_CASES("Rune display cases", Rarity.RARE, ItemID.POH_GUIDE_RUNECASE, -1),
	SHIELD_EASEL("Shield easel", Rarity.RARE, ItemID.POH_HERALDRY_BENCH_2, -1),
	COSTUME_ROOM("Costume room", Rarity.RARE, ItemID.POH_COS_ROOM_CAPE_RACK_MAGIC_STONE, -1),
	CRAFTING_TABLE_4("Crafting table 4", Rarity.RARE, ItemID.POH_CRAFTING_TABLE_4, -1),
	CRYSTAL_BALL("Crystal ball", Rarity.RARE, ItemID.POH_CRYSTALBALL_1, -1),
	FANCY_RANGE("Fancy range", Rarity.RARE, ItemID.POH_STOVE_7, -1),
	MOUNTED_SWORD("Mounted sword", Rarity.RARE, ItemID.POH_GUIDE_SWORD, -1),
	OAK_WARDROBE_COSTUME_ROOM("Oak wardrobe (costume room)", Rarity.RARE, ItemID.POH_COS_ROOM_MAGIC_WARDROBE_OAK, -1),
	STASH_UNITS_MEDIUM("STASH units (medium)", Rarity.RARE, ItemID.HH_DUMMY_HIDEYHOLE_MEDIUM, -1),
	ALCHEMICAL_CHART("Alchemical chart", Rarity.RARE, ItemID.POH_WALLCHART_1, -1),
	ANVIL("Anvil", Rarity.RARE, ItemID.PATTERN_UNLIT_CANDLE_DUMMY, -1),
	TEAK_LARDER("Teak larder", Rarity.RARE, ItemID.POH_LARDER_3, -1),
	CARVED_TEAK_DINING_BENCH("Carved teak dining bench", Rarity.RARE, ItemID.POH_DINING_CHAIRS_5, -1),
	OAK_FANCY_DRESS_BOX("Oak fancy dress box", Rarity.RARE, ItemID.POH_COS_ROOM_FANCY_DRESS_BOX_OAK, -1),
	OAK_TELESCOPE("Oak telescope", Rarity.RARE, ItemID.POH_TELESCOPE_1, -1),
	SMALL_LANDSCAPE("Small landscape", Rarity.RARE, ItemID.POH_GUIDE_LANDSCAPE1, -1),
	TEAK_PRIZE_CHEST("Teak prize chest", Rarity.RARE, ItemID.POH_PRIZE_CHEST_2, -1),
	TOOL_STORE_4("Tool store 4", Rarity.RARE, ItemID.POH_TOOL_STORE_4, -1),
	WEAPONS_RACK("Weapons rack", Rarity.RARE, ItemID.POH_WEAPON_RACK_2, -1),
	CARVED_TEAK_DINING_TABLE("Carved teak dining table", Rarity.RARE, ItemID.POH_DINING_TABLE_5, -1),
	CHAPEL("Chapel", Rarity.RARE, ItemID.POH_ALTAR_MARBLE_GILT, -1),
	ICON_OF_GNOME_CHILD("Icon of Gnome Child", Rarity.RARE, ItemID.POH_ICON_GNOMECHILD, -1),
	LARGE_TEAK_BED("Large teak bed", Rarity.RARE, ItemID.POH_BED_5, -1),
	MAPLE_TREE("Maple tree", Rarity.RARE, ItemID.POH_TREE_5, -1),
	OAK_ALTAR("Oak altar", Rarity.RARE, ItemID.POH_ALTAR_OAK, -1),
	OAK_SHELVES_2("Oak shelves 2", Rarity.RARE, ItemID.POH_KITCHEN_SHELVES_5, -1),
	STEEL_TORCHES_CHAPEL("Steel torches (chapel)", Rarity.RARE, ItemID.POH_TORCHES_STEEL, -1),
	OAK_ARMOUR_CASE("Oak armour case", Rarity.RARE, ItemID.POH_COS_ROOM_ARMOUR_CASE_OAK, -1),
	STEEL_FRAMED_WORKBENCH("Steel framed workbench", Rarity.RARE, ItemID.POH_WORKBENCH_3, -1),
	TEAK_DRESSER("Teak dresser", Rarity.RARE, ItemID.POH_MIRROR_4, -1),
	FOREST_PET_HABITAT("Forest pet habitat", Rarity.RARE, ItemID.POH_MENAGERIE_HABITAT_2, -1),
	GOLD_SINK("Gold Sink", Rarity.RARE, ItemID.POH_SINK_4, -1),
	MOUNTED_AMULET_OF_GLORY("Mounted Amulet of Glory", Rarity.RARE, ItemID.POH_TROPHY_AMULETOFGLORY, -1),
	MOUNTED_ANTI_DRAGON_SHIELD("Mounted Anti-Dragon Shield", Rarity.RARE, ItemID.POH_TROPHY_ANTIDRAGONBREATH, -1),
	MOUNTED_CAPE_OF_LEGENDS("Mounted Cape of Legends", Rarity.RARE, ItemID.POH_TROPHY_LEGENDSCAPE, -1),
	MOUNTED_MYTHICAL_CAPE("Mounted Mythical Cape", Rarity.RARE, ItemID.POH_TROPHY_MYTHICAL_CAPE, -1),
	OAK_DEMON_LECTERN("Oak demon lectern", Rarity.RARE, ItemID.POH_LECTERN_3, -1),
	OAK_EAGLE_LECTERN("Oak eagle lectern", Rarity.RARE, ItemID.POH_LECTERN_2, -1),
	SINK("Sink", Rarity.RARE, ItemID.POH_SINK_3, -1),
	CHEF_S_DELIGHT_BARREL("Chef's Delight barrel", Rarity.RARE, ItemID.POH_BARREL_6, -1),
	COMBAT_DUMMY("Combat dummy", Rarity.RARE, ItemID.POH_COMBAT_DUMMY, -1),
	LEAGUES_ACCOMPLISHMENT_SCROLL("Leagues accomplishment scroll", Rarity.RARE, ItemID.POH_LEAGUEHALL_ACCOMPLISHMENT_SCROLL, -1),
	OAK_TREASURE_CHEST("Oak treasure chest", Rarity.RARE, ItemID.POH_COS_ROOM_TREASURE_CHEST_OAK, -1),
	SYMBOL_OF_GUTHIX("Symbol of Guthix", Rarity.RARE, ItemID.POH_SYMBOL_GUTHIX, -1),
	SYMBOL_OF_SARADOMIN("Symbol of Saradomin", Rarity.RARE, ItemID.POH_SYMBOL_SARADOMIN, -1),
	SYMBOL_OF_ZAMORAK("Symbol of Zamorak", Rarity.RARE, ItemID.POH_SYMBOL_ZAMORAK, -1),
	TEAK_PET_FEEDER("Teak pet feeder", Rarity.RARE, ItemID.POH_MENAGERIE_PETFEEDER_2, -1),
	TEAK_PET_HOUSE_5_PETS("Teak pet house (5 pets)", Rarity.RARE, ItemID.POH_MENAGERIE_PETHOUSE_2, -1),
	TEAK_STAIRCASE("Teak staircase", Rarity.RARE, ItemID.POH_STAIRS_TEAK, -1),
	CHAPEL_WINDCHIMES("Chapel windchimes", Rarity.RARE, ItemID.POH_WINDCHIMES, -1),
	SHUTTERED_CHAPEL_WINDOW("Shuttered chapel window", Rarity.RARE, ItemID.POH_CHAPEL_WINDOW_SHUTTERS, -1),
	SMALL_CHAPEL_STATUE("Small chapel statue", Rarity.RARE, ItemID.POH_STATUE_SAINT, -1),
	TEAK_PET_SCRATCHING_POST("Teak pet scratching post", Rarity.RARE, ItemID.POH_MENAGERIE_SCRATCHINGPOST_2, -1),
	TREASURE_HUNT_FAIRY_HOUSE("Treasure hunt fairy house", Rarity.RARE, ItemID.POH_PARTY_GAME_2, -1),
	WOODEN_TORCHES_CHAPEL("Wooden torches (chapel)", Rarity.RARE, ItemID.POH_TORCHES_WOODEN, -1),
	DEMON_BUTLER("Demon Butler", Rarity.RARE, ItemID.GRAIL_BELL, -1),
	FIRE_OF_DEHUMIDIFICATION("Fire of Dehumidification", Rarity.RARE, ItemID.MY2ARM_DUMMY_FIRE_GHAST, -1),
	MAHOGANY_HOMES_ADEPT("Mahogany Homes (adept)", Rarity.RARE, ItemID.POH_CHINACUP_TEA, -1),
	MAHOGANY_ARMCHAIR("Mahogany armchair", Rarity.RARE, ItemID.POH_ARMCHAIR_7, -1),
	OAK_TOY_BOX("Oak toy box", Rarity.RARE, ItemID.POH_COS_ROOM_TOY_BOX_OAK, -1),
	ORNAMENTAL_GLOBE("Ornamental globe", Rarity.RARE, ItemID.POH_GLOBE_2, -1),
	PORTAL_CHAMBER("Portal chamber", Rarity.RARE, ItemID.POH_TELEPORT_CENTREPIECE_3, -1),
	ROWBOAT("Rowboat", Rarity.RARE, ItemID.PATTERN_CANDLE_LANTERN_UNLIT_DUMMY, -1),
	TEAK_ALTAR("Teak altar", Rarity.RARE, ItemID.POH_ALTAR_TEAK, -1),
	TEAK_PORTAL_FRAME("Teak portal frame", Rarity.RARE, ItemID.POH_PORTAL_FRAME_1, -1),
	CARVED_OAK_WARDROBE_COSTUME_ROOM("Carved oak wardrobe (costume room)", Rarity.RARE, ItemID.POH_COS_ROOM_MAGIC_WARDROBE_CARVED_OAK, -1),
	COMBAT_RING("Combat ring", Rarity.RARE, ItemID.POH_COMBAT_RING_3, -1),
	TEAK_CHEST_OF_DRAWERS("Teak chest of drawers", Rarity.RARE, ItemID.POH_WARDROBE_4, -1),
	MAHOGANY_DINING_BENCH("Mahogany dining bench", Rarity.RARE, ItemID.POH_DINING_CHAIRS_6, -1),
	MAHOGANY_DINING_TABLE("Mahogany dining table", Rarity.RARE, ItemID.POH_DINING_TABLE_6, -1),
	TEAK_KITCHEN_TABLE("Teak kitchen table", Rarity.RARE, ItemID.POH_KITCHENTABLE_3, -1),
	COMBAT_DUMMY_UNDEAD_AND_SLAYER("Combat dummy (Undead and Slayer)", Rarity.RARE, ItemID.POH_COMBAT_DUMMY_UNDEADSLAYER, -1),
	MAHOGANY_FOUR_POSTER_BED("Mahogany four-poster bed", Rarity.RARE, ItemID.POH_BED_6, -1),
	STEEL_CANDLESTICKS("Steel candlesticks", Rarity.RARE, ItemID.POH_CANDLESTICKS_STEEL, -1),
	DARTBOARD("Dartboard", Rarity.RARE, ItemID.POH_RANGING_GAME_2, -1),
	ELEMENTAL_SPHERE("Elemental sphere", Rarity.RARE, ItemID.POH_CRYSTALBALL_2, -1),
	EXTRA_WEAPONS_RACK("Extra weapons rack", Rarity.RARE, ItemID.POH_WEAPON_RACK_3, -1),
	MAHOGANY_PRIZE_CHEST("Mahogany prize chest", Rarity.RARE, ItemID.POH_PRIZE_CHEST_3, -1),
	OAK_CAPE_RACK("Oak cape rack", Rarity.RARE, ItemID.POH_COS_ROOM_CAPE_RACK_OAK, -1),
	ARMOUR_STAND("Armour stand", Rarity.RARE, ItemID.POH_REPAIR_BENCH_3, -1),
	BOUNDARY_STONES("Boundary stones", Rarity.RARE, ItemID.POH_FENCING1, -1),
	FORMAL_GARDEN("Formal garden", Rarity.RARE, ItemID.POH_FORMAL_GARDEN_CENTREPIECE_5, -1),
	LARGE_PORTRAIT("Large portrait", Rarity.RARE, ItemID.POH_GUIDE_PORTRAIT2, -1),
	STASH_UNITS_HARD("STASH units (hard)", Rarity.RARE, ItemID.HH_DUMMY_HIDEYHOLE_HARD, -1),
	TEAK_CLOCK("Teak clock", Rarity.RARE, ItemID.POH_CLOCK_2, -1),
	TOOL_STORE_5("Tool store 5", Rarity.RARE, ItemID.POH_TOOL_STORE_5, -1),
	CLOTH_COVERED_TEAK_ALTAR("Cloth-covered teak altar", Rarity.RARE, ItemID.POH_ALTAR_TEAK_CLOTH, -1),
	FANCY_TEAK_DRESSER("Fancy teak dresser", Rarity.RARE, ItemID.POH_MIRROR_5, -1),
	FURNACE("Furnace", Rarity.RARE, ItemID.PATTERN_HAMMER_DUMMY, -1),
	GILDED_MAHOGANY_WALL_DECORATION("Gilded mahogany wall decoration", Rarity.RARE, ItemID.POH_WALL_CREST_3, -1),
	HALLOWED_SEPULCHRE_REPAIR_BRIDGE("Hallowed Sepulchre - Repair bridge", Rarity.RARE, ItemID.HALLOWED_TOKEN, -1),
	TEAK_MOUNTED_FISH_DISPLAY("Teak mounted fish display", Rarity.RARE, ItemID.PATTERN_SWORDFISH_DUMMY, -1),
	TEAK_SHELVES_1("Teak shelves 1", Rarity.RARE, ItemID.POH_KITCHEN_SHELVES_6, -1),
	THORNY_HEDGE("Thorny hedge", Rarity.RARE, ItemID.POH_HEDGE1, -1),
	DESERT_PET_HABITAT("Desert pet habitat", Rarity.RARE, ItemID.POH_MENAGERIE_HABITAT_3, -1),
	GOLD_CANDLESTICKS("Gold candlesticks", Rarity.RARE, ItemID.POH_CANDLESTICKS_GILT, -1),
	MEDIUM_BALANCE("Medium balance", Rarity.RARE, ItemID.POH_ELEMENTAL_BALANCE_2, -1),
	TEAK_DEMON_LECTERN("Teak demon lectern", Rarity.RARE, ItemID.POH_LECTERN_5, -1),
	TEAK_EAGLE_LECTERN("Teak eagle lectern", Rarity.RARE, ItemID.POH_LECTERN_4, -1),
	CHAPEL_BELLS("Chapel bells", Rarity.RARE, ItemID.POH_BELLS, -1),
	MAHOGANY_MOUNTED_HEAD_DISPLAY("Mahogany mounted head display", Rarity.RARE, ItemID.POH_GUIDE_HEAD2, -1),
	MEDIUM_MAP("Medium map", Rarity.RARE, ItemID.POH_MAP_2, -1),
	ORNATE_COMBAT_DUMMY_UNDEAD_AND_SLAYER("Ornate combat dummy (Undead and Slayer)", Rarity.RARE, ItemID.POH_COMBAT_DUMMY_UPGRADED_1_UNDEAD, -1),
	SERVANT_S_MONEY_BAG("Servant's money bag", Rarity.RARE, ItemID.POH_SERVANT_MONEYBAG, -1),
	HANGMAN_GAME("Hangman game", Rarity.RARE, ItemID.POH_PARTY_GAME_3, -1),
	ICON_OF_GUTHIX("Icon of Guthix", Rarity.RARE, ItemID.POH_ICON_GUTHIX, -1),
	ICON_OF_SARADOMIN("Icon of Saradomin", Rarity.RARE, ItemID.POH_ICON_SARADOMIN, -1),
	ICON_OF_ZAMORAK("Icon of Zamorak", Rarity.RARE, ItemID.POH_ICON_ZAMORAK, -1),
	LIMESTONE_ATTACK_STONE("Limestone attack stone", Rarity.RARE, ItemID.POH_ATTACK_STONE_2, -1),
	LUNAR_GLOBE("Lunar globe", Rarity.RARE, ItemID.POH_GLOBE_3, -1),
	MAHOGANY_PET_FEEDER("Mahogany pet feeder", Rarity.RARE, ItemID.POH_MENAGERIE_PETFEEDER_3, -1),
	MAHOGANY_PET_HOUSE_7_PETS("Mahogany pet house (7 pets)", Rarity.RARE, ItemID.POH_MENAGERIE_PETHOUSE_3, -1),
	MAHOGANY_PET_SCRATCHING_POST("Mahogany pet scratching post", Rarity.RARE, ItemID.POH_MENAGERIE_SCRATCHINGPOST_3, -1),
	WOODEN_FENCE("Wooden fence", Rarity.RARE, ItemID.POH_FENCING2, -1),
	CHAMBERS_OF_XERIC_MEDIUM_STORAGE_UNIT("Chambers of Xeric - Medium storage unit", Rarity.EPIC, ItemID.RAIDS_STORAGE_2, -1),
	CLOTH_COVERED_MAHOGANY_ALTAR("Cloth-covered mahogany altar", Rarity.EPIC, ItemID.POH_ALTAR_MAHOGANY, -1),
	FIRE_OF_UNSEASONAL_WARMTH("Fire of Unseasonal Warmth", Rarity.EPIC, ItemID.MY2ARM_DUMMY_FIRE_GWD, -1),
	GILDED_MAHOGANY_FOUR_POSTER_BED("Gilded mahogany four-poster bed", Rarity.EPIC, ItemID.POH_BED_7, -1),
	GILDED_TEAK_BELL_PULL("Gilded teak bell pull", Rarity.EPIC, ItemID.POH_BELLPULL_3, -1),
	NICE_HEDGE("Nice hedge", Rarity.EPIC, ItemID.POH_HEDGE2, -1),
	OAK_THRONE("Oak throne", Rarity.EPIC, ItemID.POH_THRONE_1, -1),
	SPICE_RACK("Spice Rack", Rarity.EPIC, ItemID.POH_KITCHEN_RACK_1, -1),
	TEAK_WARDROBE_COSTUME_ROOM("Teak wardrobe (costume room)", Rarity.EPIC, ItemID.POH_COS_ROOM_MAGIC_WARDROBE_TEAK, -1),
	THRONE_ROOM("Throne room", Rarity.EPIC, ItemID.POH_THRONE_7, -1),
	YEW_TREE("Yew tree", Rarity.EPIC, ItemID.POH_TREE_6, -1),
	GILDED_MAHOGANY_DINING_BENCH("Gilded mahogany dining bench", Rarity.EPIC, ItemID.POH_DINING_CHAIRS_7, -1),
	OAK_INCENSE_BURNERS("Oak incense burners", Rarity.EPIC, ItemID.POH_INCENSE_BURNER_OAK, -1),
	THRONE_ROOM_FLOOR_DECORATION("Throne room floor decoration", Rarity.EPIC, ItemID.POH_THRONE_ROOM_CAGE_1, -1),
	TEAK_FANCY_DRESS_BOX("Teak fancy dress box", Rarity.EPIC, ItemID.POH_COS_ROOM_FANCY_DRESS_BOX_TEAK, -1),
	WORKBENCH_WITH_VICE("Workbench with vice", Rarity.EPIC, ItemID.POH_WORKBENCH_4, -1),
	ASTRONOMICAL_CHART("Astronomical chart", Rarity.EPIC, ItemID.POH_WALLCHART_2, -1),
	MARBLE_FIREPLACE("Marble fireplace", Rarity.EPIC, ItemID.POH_FIREPLACE_3, -1),
	SIMPLE_PET_ARENA("Simple pet arena", Rarity.EPIC, ItemID.POH_MENAGERIE_COMBATRING_1, -1),
	STONE_WALL("Stone wall", Rarity.EPIC, ItemID.POH_FENCING3, -1),
	TEAK_CAPE_RACK("Teak cape rack", Rarity.EPIC, ItemID.POH_COS_ROOM_CAPE_RACK_TEAK, -1),
	TEAK_WARDROBE_BEDROOM("Teak wardrobe (bedroom)", Rarity.EPIC, ItemID.POH_WARDROBE_5, -1),
	LIMESTONE_ALTAR("Limestone altar", Rarity.EPIC, ItemID.POH_ALTAR_LIMESTONE, -1),
	MAHOGANY_DRESSER("Mahogany dresser", Rarity.EPIC, ItemID.POH_MIRROR_6, -1),
	MOUNTED_GIANT_BLUE_KRILL("Mounted giant blue krill", Rarity.EPIC, ItemID.PATTERN_SALMON_DUMMY, -1),
	ORNATE_TROPHY_PEDESTAL("Ornate trophy pedestal", Rarity.EPIC, ItemID.POH_LEAGUEHALL_TROPHY_PEDESTAL_DECORATIVE, -1),
	SMALL_BOX_HEDGE("Small box hedge", Rarity.EPIC, ItemID.POH_HEDGE3, -1),
	TEAK_ARMOUR_CASE("Teak armour case", Rarity.EPIC, ItemID.POH_COS_ROOM_ARMOUR_CASE_TEAK, -1),
	TEAK_TELESCOPE("Teak telescope", Rarity.EPIC, ItemID.POH_TELESCOPE_2, -1),
	GAZEBO("Gazebo", Rarity.EPIC, ItemID.POH_FORMAL_GARDEN_CENTREPIECE_2, -1),
	GREATER_TELEPORT_FOCUS("Greater teleport focus", Rarity.EPIC, ItemID.POH_TELEPORT_CENTREPIECE_2, -1),
	LARGE_LANDSCAPE("Large landscape", Rarity.EPIC, ItemID.POH_GUIDE_LANDSCAPE2, -1),
	MAHOGANY_INCENSE_BURNERS("Mahogany incense burners", Rarity.EPIC, ItemID.POH_INCENSE_BURNER_MAHOGANY, -1),
	MAHOGANY_PORTAL_FRAME("Mahogany portal frame", Rarity.EPIC, ItemID.POH_PORTAL_FRAME_2, -1),
	OAK_CAGE("Oak cage", Rarity.EPIC, ItemID.POH_CAGE_DUNGEON_OAK, -1),
	OPULENT_RUG("Opulent rug", Rarity.EPIC, ItemID.POH_RUG_3, -1),
	OPULENT_RUG_LEAGUE_HALL("Opulent rug (League hall)", Rarity.EPIC, ItemID.POH_LEAGUEHALL_RUG_DECORATIVE, -1),
	OUBLIETTE("Oubliette", Rarity.EPIC, ItemID.POH_OUBLIETTE_SPIKES, -1),
	OUBLIETTE_SPIKES("Oubliette spikes", Rarity.EPIC, ItemID.POH_OUBLIETTE_SPIKES, -1),
	RESTORATION_POOL("Restoration pool", Rarity.EPIC, ItemID.POH_SUPERIOR_GARDEN_POOL_RESTORATION, -1),
	SUPERIOR_GARDEN("Superior garden", Rarity.EPIC, ItemID.POH_DUMMY_SUPERIOR_GARDEN, -1),
	TOPIARY_BUSH("Topiary bush", Rarity.EPIC, ItemID.POH_SUPERIOR_GARDEN_TOPIARY, -1),
	ZEN_THEME("Zen theme", Rarity.EPIC, ItemID.POH_SUPERIOR_GARDEN_THEME_ZEN, -1),
	BANNER_EASEL("Banner easel", Rarity.EPIC, ItemID.POH_HERALDRY_BENCH_3, -1),
	CRYSTAL_OF_POWER("Crystal of power", Rarity.EPIC, ItemID.POH_CRYSTALBALL_3, -1),
	MOUNTED_HARPOONFISH("Mounted Harpoonfish", Rarity.EPIC, ItemID.PATTERN_HARPOON_DUMMY, -1),
	ORNATE_BANNER_STAND("Ornate banner stand", Rarity.EPIC, ItemID.POH_LEAGUEHALL_BANNERSTAND_DECORATIVE, -1),
	ROSEMARY("Rosemary", Rarity.EPIC, ItemID.POH_FLOWERB1, -1),
	ROUND_WALL_MOUNTED_SHIELD("Round wall-mounted shield", Rarity.EPIC, ItemID.POH_WALL_CREST_4, -1),
	SUNFLOWER("Sunflower", Rarity.EPIC, ItemID.POH_FLOWERA1, -1),
	TEAK_GARDEN_BENCH("Teak garden bench", Rarity.EPIC, ItemID.POH_SUPERIOR_GARDEN_BENCH_TEAK, -1),
	TEAK_TREASURE_CHEST("Teak treasure chest", Rarity.EPIC, ItemID.POH_COS_ROOM_TREASURE_CHEST_TEAK, -1),
	IRON_RAILINGS("Iron railings", Rarity.EPIC, ItemID.POH_FENCING4, -1),
	LIMESTONE_SPIRAL_STAIRCASE("Limestone spiral staircase", Rarity.EPIC, ItemID.POH_SPIRALSTAIRS_LIMESTONE, -1),
	MAHOGANY_DEMON_LECTERN("Mahogany demon lectern", Rarity.EPIC, ItemID.POH_LECTERN_7, -1),
	MAHOGANY_EAGLE_LECTERN("Mahogany eagle lectern", Rarity.EPIC, ItemID.POH_LECTERN_6, -1),
	POLAR_PET_HABITAT("Polar pet habitat", Rarity.EPIC, ItemID.POH_MENAGERIE_HABITAT_4, -1),
	TEAK_SHELVES_2("Teak shelves 2", Rarity.EPIC, ItemID.POH_KITCHEN_SHELVES_7, -1),
	TEAK_THRONE("Teak throne", Rarity.EPIC, ItemID.POH_THRONE_2, -1),
	CELESTIAL_GLOBE("Celestial globe", Rarity.EPIC, ItemID.POH_GLOBE_4, -1),
	MOUNTED_GOLDEN_HADDOCK("Mounted golden haddock", Rarity.EPIC, ItemID.PATTERN_TROUT_DUMMY, -1),
	OAK_LEVER("Oak lever", Rarity.EPIC, ItemID.POH_LEVER_OAK, -1),
	OAK_OUBLIETTE_LADDER("Oak oubliette ladder", Rarity.EPIC, ItemID.POH_DUNGEON_LADDER_OAK, -1),
	ORNATE_LEAGUE_STATUE("Ornate league statue", Rarity.EPIC, ItemID.POH_LEAGUEHALL_STATUE_DECORATIVE, -1),
	STEEL_CAGE("Steel cage", Rarity.EPIC, ItemID.POH_THRONE_ROOM_CAGE_2, -1),
	TEAK_TOY_BOX("Teak toy box", Rarity.EPIC, ItemID.POH_COS_ROOM_TOY_BOX_TEAK, -1),
	TOPIARY_HEDGE("Topiary hedge", Rarity.EPIC, ItemID.POH_HEDGE4, -1),
	CARVED_TEAK_WARDROBE_COSTUME_ROOM("Carved teak wardrobe (costume room)", Rarity.EPIC, ItemID.POH_COS_ROOM_MAGIC_WARDROBE_TEAK_CARVED, -1),
	CHAPEL_ORGAN("Chapel organ", Rarity.EPIC, ItemID.POH_ORGAN, -1),
	DECORATIVE_CHAPEL_WINDOW("Decorative chapel window", Rarity.EPIC, ItemID.POH_CHAPEL_WINDOW_DECORATIVE, -1),
	MARBLE_INCENSE_BURNER("Marble incense burner", Rarity.EPIC, ItemID.POH_INCENSE_BURNER_MARBLE, -1),
	MEDIUM_CHAPEL_STATUE("Medium chapel statue", Rarity.EPIC, ItemID.POH_STATUE_ANGEL, -1),
	BANK_CHEST("Bank chest", Rarity.EPIC, ItemID.PATTERN_FRUIT_BLAST_DUMMY, -1),
	CONSECRATED_PET_HOUSE_9_PETS("Consecrated pet house (9 pets)", Rarity.EPIC, ItemID.POH_MENAGERIE_PETHOUSE_4, -1),
	DUNGEON("Dungeon", Rarity.EPIC, ItemID.POH_DUNGEON_DOOR_STEEL, -1),
	DUNGEON_ENTRANCE("Dungeon entrance", Rarity.EPIC, ItemID.POH_GARDEN_CENTREPIECE_5, -1),
	MAHOGANY_HOMES_EXPERT("Mahogany Homes (expert)", Rarity.EPIC, ItemID.POH_GILTCHINACUP_TEA, -1),
	MARBLE_ALTAR("Marble altar", Rarity.EPIC, ItemID.POH_ALTAR_MARBLE, -1),
	OAK_AND_STEEL_CAGE("Oak and steel cage", Rarity.EPIC, ItemID.POH_CAGE_DUNGEON_OAK_STEEL, -1),
	REVITALISATION_POOL("Revitalisation pool", Rarity.EPIC, ItemID.POH_SUPERIOR_GARDEN_POOL_REVITALISATION, -1),
	SKELETON_GUARD("Skeleton guard", Rarity.EPIC, ItemID.POH_SKELETON_GUARD, -1),
	DAFFODILS("Daffodils", Rarity.EPIC, ItemID.POH_FLOWERB2, -1),
	ICON_OF_BOB_THE_CAT("Icon of Bob the Cat", Rarity.EPIC, ItemID.POH_ICON_BOB, -1),
	MARIGOLDS("Marigolds", Rarity.EPIC, ItemID.POH_FLOWERA2, -1),
	PICKET_FENCE("Picket fence", Rarity.EPIC, ItemID.POH_FENCING5, -1),
	RANGING_PEDESTALS("Ranging pedestals", Rarity.EPIC, ItemID.POH_COMBAT_RING_4, -1),
	SMALL_FOUNTAIN("Small fountain", Rarity.EPIC, ItemID.POH_FORMAL_GARDEN_CENTREPIECE_3, -1),
	TENTACLE_POOL("Tentacle pool", Rarity.EPIC, ItemID.POH_OUBLIETTE_POOL, -1),
	DECORATIVE_DUNGEON_BLOODSTAIN("Decorative dungeon bloodstain", Rarity.EPIC, ItemID.POH_DUNGEON_BLOODSTAIN, -1),
	DUNGEON_CANDLES("Dungeon candles", Rarity.EPIC, ItemID.POH_DUNGEON_CANDLE, -1),
	FANCY_HEDGE("Fancy hedge", Rarity.EPIC, ItemID.POH_HEDGE5, -1),
	GILDED_MAHOGANY_AND_MARBLE_TABLE("Gilded mahogany and marble table", Rarity.EPIC, ItemID.POH_DINING_TABLE_7, -1),
	MAHOGANY_CAPE_RACK("Mahogany cape rack", Rarity.EPIC, ItemID.POH_COS_ROOM_CAPE_RACK_MAHOGANY, -1),
	MARBLE_PORTAL_NEXUS("Marble portal nexus", Rarity.EPIC, ItemID.POH_PORTAL_NEXUS_1, -1),
	MOUNTED_XERIC_S_TALISMAN("Mounted Xeric's Talisman", Rarity.EPIC, ItemID.POH_AMULET_XERIC, -1),
	PORTAL_NEXUS("Portal nexus", Rarity.EPIC, ItemID.POH_PORTAL_NEXUS_1, -1),
	SPIKE_TRAP("Spike trap", Rarity.EPIC, ItemID.POH_SPIKE_TRAP, -1),
	ADVANCED_PET_ARENA("Advanced pet arena", Rarity.EPIC, ItemID.POH_MENAGERIE_COMBATRING_2, -1),
	RAGING_ECHOES_RUG("Raging Echoes rug", Rarity.EPIC, ItemID.POH_RUG_LEAGUE_5, -1),
	GILDED_MAHOGANY_DRESSER("Gilded Mahogany dresser", Rarity.EPIC, ItemID.POH_MIRROR_7, -1),
	GUARD_DOG("Guard dog", Rarity.EPIC, ItemID.POH_GUARD_DOG, -1),
	LARGE_TRAPDOOR("Large trapdoor", Rarity.EPIC, ItemID.POH_THRONE_ROOM_CAGE_3, -1),
	MAHOGANY_OUTFIT_STAND("Mahogany outfit stand", Rarity.EPIC, ItemID.POH_LEAGUEHALL_OUTFITSTAND_MAHOGANY, -1),
	MAHOGANY_THRONE("Mahogany throne", Rarity.EPIC, ItemID.POH_THRONE_3, -1),
	MOUNTED_ORANGEFIN("Mounted orangefin", Rarity.EPIC, ItemID.PATTERN_PIKE_DUMMY, -1),
	OAK_DUNGEON_DOOR("Oak dungeon door", Rarity.EPIC, ItemID.POH_DUNGEON_DOOR_OAK, -1),
	DEMON("Demon", Rarity.EPIC, ItemID.POH_DEMON, -1),
	GARDEN_FENCE("Garden fence", Rarity.EPIC, ItemID.POH_FENCING6, -1),
	GILDED_MARBLE_ALTAR("Gilded marble altar", Rarity.EPIC, ItemID.POH_ALTAR_MARBLE_GILT, -1),
	LARGE_FOUNTAIN("Large fountain", Rarity.EPIC, ItemID.POH_FORMAL_GARDEN_CENTREPIECE_4, -1),
	MAGIC_TREE("Magic tree", Rarity.EPIC, ItemID.POH_TREE_7, -1),
	MAHOGANY_WARDROBE_BEDROOM("Mahogany wardrobe (bedroom)", Rarity.EPIC, ItemID.POH_WARDROBE_6, -1),
	OTHERWORLDLY_THEME("Otherworldly theme", Rarity.EPIC, ItemID.POH_SUPERIOR_GARDEN_THEME_ZANARIS, -1),
	REDWOOD_FENCE("Redwood fence", Rarity.EPIC, ItemID.POH_SUPERIOR_GARDEN_REDWOOD_FENCE, -1),
	SPIRIT_TREE("Spirit tree", Rarity.EPIC, ItemID.POH_SUPERIOR_GARDEN_TELEPORT_TREE, -1),
	TREASURE_ROOM("Treasure room", Rarity.EPIC, ItemID.POH_TREASURE_MAHOGANY, -1),
	WOODEN_DUNGEON_TREASURE_CRATE("Wooden dungeon treasure crate", Rarity.EPIC, ItemID.POH_TREASURE_WOOD, -1),
	BLUEBELLS("Bluebells", Rarity.EPIC, ItemID.POH_FLOWERB3, -1),
	MAHOGANY_MOUNTED_FISH_DISPLAY("Mahogany mounted fish display", Rarity.EPIC, ItemID.PATTERN_SHARK_DUMMY, -1),
	MAN_TRAP("Man trap", Rarity.EPIC, ItemID.POH_MAN_TRAP, -1),
	ROSES("Roses", Rarity.EPIC, ItemID.POH_FLOWERA3, -1),
	SQUARE_WALL_MOUNTED_SHIELD("Square wall-mounted shield", Rarity.EPIC, ItemID.POH_WALL_CREST_5, -1),
	TALL_FANCY_HEDGE("Tall fancy hedge", Rarity.EPIC, ItemID.POH_HEDGE6, -1),
	ARMILLARY_SPHERE("Armillary sphere", Rarity.EPIC, ItemID.POH_GLOBE_5, -1),
	GNOME_BENCH("Gnome bench", Rarity.EPIC, ItemID.POH_SUPERIOR_GARDEN_BENCH_MAHOGANY, -1),
	GREATER_MAGICAL_BALANCE("Greater magical balance", Rarity.EPIC, ItemID.POH_ELEMENTAL_BALANCE_3, -1),
	MARBLE_LECTERN("Marble lectern", Rarity.EPIC, ItemID.POH_LECTERN_8, -1),
	OUBLIETTE_FLAME_PIT("Oubliette flame pit", Rarity.EPIC, ItemID.POH_OUBLIETTE_FIRE, -1),
	STASH_UNITS_ELITE("STASH units (elite)", Rarity.EPIC, ItemID.HH_DUMMY_HIDEYHOLE_ELITE, -1),
	VOLCANIC_PET_HABITAT("Volcanic pet habitat", Rarity.EPIC, ItemID.POH_MENAGERIE_HABITAT_5, -1),
	WORKBENCH_WITH_LATHE("Workbench with lathe", Rarity.EPIC, ItemID.POH_WORKBENCH_5, -1),
	GILDED_MOUNTED_HEAD_DISPLAY("Gilded mounted head display", Rarity.EPIC, ItemID.POH_GUIDE_HEAD3, -1),
	HOBGOBLIN_GUARD("Hobgoblin guard", Rarity.EPIC, ItemID.POH_HOBGOBLIN, -1),
	LARGE_MAP("Large map", Rarity.EPIC, ItemID.POH_MAP_3, -1),
	MAHOGANY_TROPHY_CASE("Mahogany trophy case", Rarity.EPIC, ItemID.POH_LEAGUEHALL_TROPHYCASE_MAHOGANY, -1),
	MAHOGANY_WARDROBE_COSTUME_ROOM("Mahogany wardrobe (costume room)", Rarity.EPIC, ItemID.POH_COS_ROOM_MAGIC_WARDROBE_MAHOGANY, -1),
	MOUNTED_HUGE_HALIBUT("Mounted huge halibut", Rarity.EPIC, ItemID.PATTERN_HERRING_DUMMY, -1),
	TEAK_LEVER("Teak lever", Rarity.EPIC, ItemID.POH_LEVER_TEAK, -1),
	TEAK_OUBLIETTE_LADDER("Teak oubliette ladder", Rarity.EPIC, ItemID.POH_DUNGEON_LADDER_TEAK, -1),
	MARBLE_ATTACK_STONE("Marble attack stone", Rarity.EPIC, ItemID.POH_ATTACK_STONE_3, -1),
	MARBLE_WALL("Marble wall", Rarity.EPIC, ItemID.POH_FENCING7, -1),
	OAK_DUNGEON_TREASURE_CHEST("Oak dungeon treasure chest", Rarity.EPIC, ItemID.POH_TREASURE_OAK, -1),
	ACHIEVEMENT_GALLERY("Achievement Gallery", Rarity.LEGENDARY, ItemID.POH_ACHIEVEMENTGALLERY_ADVENTURELOG_3, -1),
	ANCIENT_ALTAR("Ancient Altar", Rarity.LEGENDARY, ItemID.POH_ACHIEVEMENTGALLERY_ALTAR_ANCIENT, -1),
	CAPE_HANGER("Cape hanger", Rarity.LEGENDARY, ItemID.POH_ACHIEVEMENTGALLERY_MOUNTEDDISPLAY_CAPESTAND, -1),
	DARK_ALTAR("Dark Altar", Rarity.LEGENDARY, ItemID.POH_ACHIEVEMENTGALLERY_ALTAR_ARCEUUS, -1),
	KALPHITE_SOLDIER("Kalphite soldier", Rarity.LEGENDARY, ItemID.POH_KALPHITE_SOLDIER, -1),
	LUNAR_ALTAR("Lunar Altar", Rarity.LEGENDARY, ItemID.POH_ACHIEVEMENTGALLERY_ALTAR_LUNAR, -1),
	MAHOGANY_FANCY_DRESS_BOX("Mahogany fancy dress box", Rarity.LEGENDARY, ItemID.POH_COS_ROOM_FANCY_DRESS_BOX_MAHOGANY, -1),
	MARBLE_PORTAL_FRAME("Marble portal frame", Rarity.LEGENDARY, ItemID.POH_PORTAL_FRAME_3, -1),
	MOUNTED_COINS("Mounted coins", Rarity.LEGENDARY, ItemID.POH_ACHIEVEMENTGALLERY_MOUNTEDDISPLAY_COINS, -1),
	MOUNTED_EMBLEM("Mounted emblem", Rarity.LEGENDARY, ItemID.POH_ACHIEVEMENTGALLERY_MOUNTEDDISPLAY_EMBLEM, -1),
	OBELISK("Obelisk", Rarity.LEGENDARY, ItemID.POH_SUPERIOR_GARDEN_WILDERNESS_OBELISK, -1),
	QUEST_LIST("Quest list", Rarity.LEGENDARY, ItemID.POH_ACHIEVEMENTGALLERY_QUESTLIST, -1),
	REJUVENATION_POOL("Rejuvenation pool", Rarity.LEGENDARY, ItemID.POH_SUPERIOR_GARDEN_POOL_REJUVENATION, -1),
	SCRYING_POOL("Scrying pool", Rarity.LEGENDARY, ItemID.POH_TELEPORT_CENTREPIECE_3, -1),
	SPIKED_CAGE("Spiked cage", Rarity.LEGENDARY, ItemID.POH_CAGE_DUNGEON_STEEL_SPIKES, -1),
	TALL_BOX_HEDGE("Tall box hedge", Rarity.LEGENDARY, ItemID.POH_HEDGE7, -1),
	TANGLE_VINE("Tangle vine", Rarity.LEGENDARY, ItemID.POH_VINE_TRAP, -1),
	ARCHERY_TARGET("Archery target", Rarity.LEGENDARY, ItemID.POH_RANGING_GAME_3, -1),
	BALANCE_BEAM("Balance beam", Rarity.LEGENDARY, ItemID.POH_COMBAT_RING_5, -1),
	BASIC_JEWELLERY_BOX("Basic jewellery box", Rarity.LEGENDARY, ItemID.POH_ACHIEVEMENTGALLERY_JEWELLERYBOX_1, -1),
	DESECRATED_PET_HOUSE_12_PETS("Desecrated pet house (12 pets)", Rarity.LEGENDARY, ItemID.POH_MENAGERIE_PETHOUSE_5, -1),
	GILDED_MAHOGANY_CAPE_RACK("Gilded mahogany cape rack", Rarity.LEGENDARY, ItemID.POH_COS_ROOM_CAPE_RACK_MAHOGANY_GILDED, -1),
	GILDED_MAHOGANY_THRONE("Gilded mahogany throne", Rarity.LEGENDARY, ItemID.POH_THRONE_4, -1),
	POSH_FOUNTAIN("Posh fountain", Rarity.LEGENDARY, ItemID.POH_FORMAL_GARDEN_CENTREPIECE_5, -1),
	BABY_RED_DRAGON("Baby red dragon", Rarity.LEGENDARY, ItemID.POH_DRAGON, -1),
	GILDED_PORTAL_NEXUS("Gilded portal nexus", Rarity.LEGENDARY, ItemID.POH_PORTAL_NEXUS_2, -1),
	LESSER_MAGIC_CAGE("Lesser magic cage", Rarity.LEGENDARY, ItemID.POH_THRONE_ROOM_CAGE_4, -1),
	MAHOGANY_ARMOUR_CASE("Mahogany armour case", Rarity.LEGENDARY, ItemID.POH_COS_ROOM_ARMOUR_CASE_MAHOGANY, -1),
	MARBLE_STAIRCASE("Marble staircase", Rarity.LEGENDARY, ItemID.POH_STAIRS_MARBLE, -1),
	MOUNTED_ALCHEMICAL_HYDRA_HEAD("Mounted Alchemical Hydra head", Rarity.LEGENDARY, ItemID.POH_TROPHY_ALCHEMICAL_HYDRA_HEAD, -1),
	MOUNTED_DIGSITE_PENDANT("Mounted Digsite Pendant", Rarity.LEGENDARY, ItemID.POH_AMULET_DIGSITE, -1),
	MOUNTED_VORKATH_HEAD("Mounted Vorkath head", Rarity.LEGENDARY, ItemID.POH_TROPHY_VORKATH, -1),
	MOUNTED_PURPLEFIN("Mounted purplefin", Rarity.LEGENDARY, ItemID.PATTERN_SARDINE_DUMMY, -1),
	DECORATIVE_DUNGEON_PIPE("Decorative dungeon pipe", Rarity.LEGENDARY, ItemID.POH_DUNGEON_PIPE, -1),
	GLORIOUS_PET_ARENA("Glorious pet arena", Rarity.LEGENDARY, ItemID.POH_MENAGERIE_COMBATRING_3, -1),
	INFERNAL_CHART("Infernal chart", Rarity.LEGENDARY, ItemID.POH_WALLCHART_3, -1),
	MAHOGANY_ADVENTURE_LOG("Mahogany adventure log", Rarity.LEGENDARY, ItemID.POH_ACHIEVEMENTGALLERY_ADVENTURELOG_1, -1),
	OBSIDIAN_FENCE("Obsidian fence", Rarity.LEGENDARY, ItemID.POH_SUPERIOR_GARDEN_OBSIDIAN_FENCE, -1),
	ROCNAR("Rocnar", Rarity.LEGENDARY, ItemID.POH_OUB_MONSTER1, -1),
	TEAK_DUNGEON_TREASURE_CHEST("Teak dungeon treasure chest", Rarity.LEGENDARY, ItemID.POH_TREASURE_TEAK, -1),
	DUNGEON_TORCHES("Dungeon torches", Rarity.LEGENDARY, ItemID.POH_DUNGEON_TORCH, -1),
	MAHOGANY_TELESCOPE("Mahogany telescope", Rarity.LEGENDARY, ItemID.POH_TELESCOPE_3, -1),
	MARBLE_TRAP("Marble trap", Rarity.LEGENDARY, ItemID.POH_MARBLE_TRAP, -1),
	STEEL_PLATED_OAK_DOOR("Steel-plated oak door", Rarity.LEGENDARY, ItemID.POH_DUNGEON_DOOR_STEEL, -1),
	BONE_CAGE("Bone cage", Rarity.LEGENDARY, ItemID.POH_CAGE_DUNGEON_BONES, -1),
	FAIRY_RING("Fairy ring", Rarity.LEGENDARY, ItemID.POH_SUPERIOR_GARDEN_TELEPORT_RING, -1),
	FANCY_REJUVENATION_POOL("Fancy rejuvenation pool", Rarity.LEGENDARY, ItemID.POH_SUPERIOR_GARDEN_POOL_RECOVERY, -1),
	GILDED_MAHOGANY_CLOCK("Gilded mahogany clock", Rarity.LEGENDARY, ItemID.POH_CLOCK_3, -1),
	TOK_XIL("Tok-Xil", Rarity.LEGENDARY, ItemID.POH_TOK_XIL, -1),
	VOLCANIC_THEME("Volcanic theme", Rarity.LEGENDARY, ItemID.POH_SUPERIOR_GARDEN_THEME_TZHAAR, -1),
	FANCY_JEWELLERY_BOX("Fancy jewellery box", Rarity.LEGENDARY, ItemID.POH_ACHIEVEMENTGALLERY_JEWELLERYBOX_2, -1),
	HUGE_SPIDER("Huge spider", Rarity.LEGENDARY, ItemID.POH_SPIDER, -1),
	MAHOGANY_TOY_BOX("Mahogany toy box", Rarity.LEGENDARY, ItemID.POH_COS_ROOM_TOY_BOX_MAHOGANY, -1),
	MOUNTED_SWIFT_MARLIN("Mounted swift marlin", Rarity.LEGENDARY, ItemID.PATTERN_COD_DUMMY, -1),
	SMALL_ORRERY("Small orrery", Rarity.LEGENDARY, ItemID.POH_GLOBE_6, -1),
	WALL_MOUNTED_KITESHIELD("Wall-mounted kiteshield", Rarity.LEGENDARY, ItemID.POH_WALL_CREST_6, -1),
	BOSS_LAIR_DISPLAY("Boss lair display", Rarity.LEGENDARY, ItemID.POH_ACHIEVEMENTGALLERY_BOSSLAIR_BLANK, -1),
	GILDED_MAHOGANY_WARDROBE_BEDROOM("Gilded mahogany wardrobe (bedroom)", Rarity.LEGENDARY, ItemID.POH_WARDROBE_7, -1),
	GILDED_MAHOGANY_WARDROBE_COSTUME_ROOM("Gilded mahogany wardrobe (costume room)", Rarity.LEGENDARY, ItemID.POH_COS_ROOM_MAGIC_WARDROBE_MAHOGANY_GILDED, -1),
	MAHOGANY_DUNGEON_TREASURE_CHEST("Mahogany dungeon treasure chest", Rarity.LEGENDARY, ItemID.POH_TREASURE_MAHOGANY, -1),
	GILDED_ADVENTURE_LOG("Gilded adventure log", Rarity.LEGENDARY, ItemID.POH_ACHIEVEMENTGALLERY_ADVENTURELOG_2, -1),
	MAHOGANY_LEVER("Mahogany lever", Rarity.LEGENDARY, ItemID.POH_LEVER_MAG, -1),
	MAHOGANY_OUBLIETTE_LADDER("Mahogany oubliette ladder", Rarity.LEGENDARY, ItemID.POH_DUNGEON_LADDER_MAG, -1),
	MARBLE_GARDEN_BENCH_DECORATION_ONLY("Marble garden bench (decoration only)", Rarity.LEGENDARY, ItemID.POH_SUPERIOR_GARDEN_BENCH_MARBLE, -1),
	STASH_UNITS_MASTER("STASH units (master)", Rarity.LEGENDARY, ItemID.HH_DUMMY_HIDEYHOLE_MASTER, -1),
	SKELETON_THRONE("Skeleton throne", Rarity.LEGENDARY, ItemID.POH_THRONE_5, -1),
	TELEPORT_TRAP("Teleport trap", Rarity.LEGENDARY, ItemID.POH_TELEPORT_TRAP, -1),
	GREATER_MAGIC_CAGE("Greater magic cage", Rarity.LEGENDARY, ItemID.POH_THRONE_ROOM_CAGE_5, -1),
	LARGE_CHAPEL_STATUE("Large chapel statue", Rarity.LEGENDARY, ItemID.POH_STATUE_GOD, -1),
	STAINED_GLASS_CHAPEL_WINDOW("Stained-glass chapel window", Rarity.LEGENDARY, ItemID.POH_CHAPEL_WINDOW_STAINEDGLASS, -1),
	CHAMBERS_OF_XERIC_LARGE_STORAGE_UNIT("Chambers of Xeric - Large storage unit", Rarity.LEGENDARY, ItemID.RAIDS_STORAGE_3, -1),
	DAGANNOTH("Dagannoth", Rarity.LEGENDARY, ItemID.POH_DAGGANOTH, -1),
	MARBLE_CAPE_RACK("Marble cape rack", Rarity.LEGENDARY, ItemID.POH_COS_ROOM_CAPE_RACK_MARBLE, -1),
	OCCULT_ALTAR_UPGRADE_FROM_ANCIENT("Occult Altar (upgrade from Ancient)", Rarity.LEGENDARY, ItemID.POH_ACHIEVEMENTGALLERY_ALTAR_ECUMENICAL_FROMANCIENT, -1),
	ORNATE_REJUVENATION_POOL("Ornate rejuvenation pool", Rarity.LEGENDARY, ItemID.POH_SUPERIOR_GARDEN_POOL_REGENERATION, -1),
	TROLL_GUARD("Troll guard", Rarity.LEGENDARY, ItemID.POH_TROLL, -1),
	MAGIC_DUNGEON_TREASURE_CHEST("Magic dungeon treasure chest", Rarity.LEGENDARY, ItemID.POH_TREASURE_MAGIC, -1),
	ORNATE_JEWELLERY_BOX("Ornate jewellery box", Rarity.LEGENDARY, ItemID.POH_ACHIEVEMENTGALLERY_JEWELLERYBOX_3, -1),
	CRYSTALLINE_PORTAL_NEXUS("Crystalline portal nexus", Rarity.LEGENDARY, ItemID.POH_PORTAL_NEXUS_3, -1),
	NATURAL_PET_HOUSE_MANY_PETS("Natural pet house (many pets)", Rarity.LEGENDARY, ItemID.POH_MENAGERIE_PETHOUSE_6, -1),
	MARBLE_ADVENTURE_LOG("Marble adventure log", Rarity.LEGENDARY, ItemID.POH_ACHIEVEMENTGALLERY_ADVENTURELOG_3, -1),
	DUNGEON_SKULL_TORCHES("Dungeon skull torches", Rarity.LEGENDARY, ItemID.POH_DUNGEON_SKULLTORCH, -1),
	HANGING_DUNGEON_SKELETON("Hanging dungeon skeleton", Rarity.LEGENDARY, ItemID.POH_DUNGEON_SKELETON_DECORATIVE, -1),
	HELLHOUND("Hellhound", Rarity.LEGENDARY, ItemID.POH_HELLHOUND, -1),
	MARBLE_DUNGEON_DOOR("Marble dungeon door", Rarity.LEGENDARY, ItemID.POH_DUNGEON_DOOR_MARBLE, -1),
	CRYSTAL_THRONE("Crystal throne", Rarity.LEGENDARY, ItemID.POH_THRONE_6, -1),
	LARGE_ORRERY("Large orrery", Rarity.LEGENDARY, ItemID.POH_GLOBE_7, -1),
	SPIRIT_TREE_FAIRY_RING("Spirit tree & fairy ring", Rarity.LEGENDARY, ItemID.POH_SUPERIOR_GARDEN_TELEPORT_TREERING, -1),
	STEEL_DRAGON("Steel dragon", Rarity.LEGENDARY, ItemID.POH_STEEL_DRAGON, -1),
	MARBLE_WARDROBE_COSTUME_ROOM("Marble wardrobe (costume room)", Rarity.LEGENDARY, ItemID.POH_COS_ROOM_MAGIC_WARDROBE_MARBLE, -1),
	MARBLE_SPIRAL("Marble spiral", Rarity.LEGENDARY, ItemID.POH_SPIRALSTAIRS_MARBLE, -1),
	OBSIDIAN_GARDEN_BENCH_DECORATION_ONLY("Obsidian garden bench (decoration only)", Rarity.LEGENDARY, ItemID.POH_SUPERIOR_GARDEN_BENCH_OBSIDIAN, -1),
	CHAMBERS_OF_XERIC_MASSIVE_STORAGE_UNIT("Chambers of Xeric - Massive storage unit", Rarity.LEGENDARY, ItemID.RAIDS_STORAGE_4, -1),
	DEMONIC_THRONE("Demonic throne", Rarity.LEGENDARY, ItemID.POH_THRONE_7, -1),
	MAGIC_STONE_CAPE_RACK("Magic stone cape rack", Rarity.LEGENDARY, ItemID.POH_COS_ROOM_CAPE_RACK_MAGIC_STONE, -1),
	RUNE_DRAGON("Rune dragon", Rarity.LEGENDARY, ItemID.POH_RUNE_DRAGON, -1),
	SKILLCAPE("Skillcape", Rarity.LEGENDARY, ItemID.SKILLCAPE_CONSTRUCTION, -1);

	private final Card card;

	ConstructionCards(String name, Rarity rarity, int itemId, int spriteId)
	{
		this.card = CardGroup.build(CardSet.CONSTRUCTION, name, rarity, itemId, spriteId);
	}

	@Override
	public Card getCard()
	{
		return card;
	}
}
