/*
 * Copyright (c) 2026, Zoinkwiz <https://github.com/Zoinkwiz>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package com.dopaminesimulator.cards.sets;

import com.dopaminesimulator.cards.Card;
import com.dopaminesimulator.cards.CardGroup;
import com.dopaminesimulator.cards.CardSet;
import com.dopaminesimulator.cards.Rarity;
import net.runelite.api.gameval.ItemID;
import net.runelite.api.gameval.SpriteID;

public enum CraftingCards implements CardGroup
{
	BEER_GLASS("Beer glass", Rarity.COMMON, ItemID.BEER_GLASS, -1),
	CUT_OPAL("Cut opal", Rarity.COMMON, ItemID.OPAL, -1),
	LEATHER_GLOVES("Leather gloves", Rarity.COMMON, ItemID.LEATHER_GLOVES, -1),
	OPAL_RING("Opal ring", Rarity.COMMON, ItemID.OPAL_RING, -1),
	POT("Pot", Rarity.COMMON, ItemID.POT_EMPTY, -1),
	SPIN_WOOL_INTO_BALLS_OF_WOOL("Spin wool into balls of wool", Rarity.COMMON, ItemID.BALL_OF_WOOL, -1),
	PHEASANT_CLOTHING("Pheasant clothing", Rarity.COMMON, ItemID.FORESTRY_PHEASANT_HAT, -1),
	CUP("Cup", Rarity.COMMON, ItemID.CUP_EMPTY, -1),
	POLISHED_BUTTONS("Polished buttons", Rarity.COMMON, ItemID.ANMA_P_BUTTONS, -1),
	CANDLE_LANTERN("Candle lantern", Rarity.COMMON, ItemID.CANDLE_LANTERN_EMPTY, -1),
	CRAFT_A_BIRDHOUSE_TRAP_FROM_NORMAL_LOGS("Craft a birdhouse trap from normal logs", Rarity.COMMON, ItemID.BIRDHOUSE_NORMAL, -1),
	GOLD_RING("Gold ring", Rarity.COMMON, ItemID.GOLD_RING, -1),
	GOLD_NECKLACE("Gold necklace", Rarity.COMMON, ItemID.GOLD_NECKLACE, -1),
	GOLD_BRACELET("Gold bracelet", Rarity.COMMON, ItemID.JEWL_GOLD_BRACELET, -1),
	LEATHER_BOOTS("Leather boots", Rarity.COMMON, ItemID.LEATHER_BOOTS, -1),
	PIE_DISH("Pie dish", Rarity.COMMON, ItemID.PIEDISH, -1),
	BOWL("Bowl", Rarity.COMMON, ItemID.BOWL_EMPTY, -1),
	GOLD_AMULET("Gold amulet", Rarity.COMMON, ItemID.STRUNG_GOLD_AMULET, -1),
	LEATHER_COWL("Leather cowl", Rarity.COMMON, ItemID.LEATHER_COWL, -1),
	EXTRACT_SINEW_FROM_MONKEY_TAILS("Extract sinew from monkey tails", Rarity.COMMON, ItemID.DAMAGED_BALLISTA_ROPE, -1),
	SPIN_FLAX_INTO_BOW_STRINGS("Spin flax into bow strings", Rarity.COMMON, ItemID.BOW_STRING, -1),
	SPIN_SINEW_INTO_CROSSBOW_STRINGS("Spin sinew into crossbow strings", Rarity.COMMON, ItemID.XBOWS_CROSSBOW_STRING, -1),
	LEATHER_VAMBRACES("Leather vambraces", Rarity.COMMON, ItemID.LEATHER_VAMBRACES, -1),
	BOLT_OF_LINEN("Bolt of linen", Rarity.COMMON, ItemID.BOLT_OF_LINEN, -1),
	CRAFT_A_GEM_POUCH("Craft a gem pouch", Rarity.COMMON, ItemID.GEM_POUCH, -1),
	OIL_LAMP("Oil lamp", Rarity.COMMON, ItemID.OIL_LAMP_EMPTY, -1),
	SPIN_FLAX_INTO_LINEN_YARN("Spin flax into linen yarn", Rarity.COMMON, ItemID.LINEN_YARN, -1),
	CUT_JADE("Cut jade", Rarity.COMMON, ItemID.JADE, -1),
	JADE_RING("Jade ring", Rarity.COMMON, ItemID.JADE_RING, -1),
	LEATHER_BODY("Leather body", Rarity.COMMON, ItemID.LEATHER_ARMOUR, -1),
	XERICIAN_HAT("Xerician hat", Rarity.COMMON, ItemID.XERIC_HAT, -1),
	CRAB_SHELL_ARMOUR("Crab shell armour", Rarity.COMMON, ItemID.HUNDRED_PIRATE_CRAB_SHELL_HELM, -1),
	CRAFT_A_BIRDHOUSE_TRAP_FROM_OAK_LOGS("Craft a birdhouse trap from oak logs", Rarity.COMMON, ItemID.BIRDHOUSE_OAK, -1),
	SNAIL_HELMET("Snail helmet", Rarity.COMMON, ItemID.SNELM_ROUND_SWAMP, -1),
	CUT_RED_TOPAZ("Cut red topaz", Rarity.COMMON, ItemID.RED_TOPAZ, -1),
	HOLY_SYMBOL("Holy symbol", Rarity.COMMON, ItemID.STRINGSTAR, -1),
	OPAL_NECKLACE("Opal necklace", Rarity.COMMON, ItemID.OPAL_NECKLACE, -1),
	RED_TOPAZ_RING("Red topaz ring", Rarity.COMMON, ItemID.TOPAZ_RING, -1),
	UNHOLY_SYMBOL("Unholy symbol", Rarity.COMMON, ItemID.STRINGSNAKE, -1),
	XERICIAN_ROBE("Xerician robe", Rarity.COMMON, ItemID.XERIC_ROBE, -1),
	LEATHER_CHAPS("Leather chaps", Rarity.COMMON, ItemID.LEATHER_CHAPS, -1),
	SILVER_SICKLE("Silver sickle", Rarity.COMMON, ItemID.SILVER_SICKLE, -1),
	PLANT_POT("Plant pot", Rarity.COMMON, ItemID.PLANTPOT_EMPTY, -1),
	SPIN_MAGIC_TREE_ROOTS_INTO_MAGIC_STRINGS("Spin magic tree roots into magic strings", Rarity.COMMON, ItemID.MAGIC_STRING, -1),
	CUT_SAPPHIRE("Cut sapphire", Rarity.UNCOMMON, ItemID.SAPPHIRE, -1),
	SAPPHIRE_RING("Sapphire ring", Rarity.UNCOMMON, ItemID.SAPPHIRE_RING, -1),
	SILVER_CROSSBOW_BOLTS("Silver crossbow bolts", Rarity.UNCOMMON, ItemID.XBOWS_CROSSBOW_BOLTS_SILVER_UNFEATHERED_5, -1),
	VEGETABLE_SACK("Vegetable sack", Rarity.UNCOMMON, ItemID.SACK_EMPTY, -1),
	OPAL_BRACELET("Opal bracelet", Rarity.UNCOMMON, ItemID.OPAL_BRACELET, -1),
	SAPPHIRE_NECKLACE("Sapphire necklace", Rarity.UNCOMMON, ItemID.SAPPHIRE_NECKLACE, -1),
	XERICIAN_TOP("Xerician top", Rarity.UNCOMMON, ItemID.XERIC_TOP, -1),
	SAPPHIRE_BRACELET("Sapphire bracelet", Rarity.UNCOMMON, ItemID.JEWL_SAPPHIRE_BRACELET, -1),
	TIARA("Tiara", Rarity.UNCOMMON, ItemID.TIARA, -1),
	SAPPHIRE_AMULET("Sapphire amulet", Rarity.UNCOMMON, ItemID.STRUNG_SAPPHIRE_AMULET, -1),
	CRAFT_A_BIRDHOUSE_TRAP_FROM_WILLOW_LOGS("Craft a birdhouse trap from willow logs", Rarity.UNCOMMON, ItemID.BIRDHOUSE_WILLOW, -1),
	JADE_NECKLACE("Jade necklace", Rarity.UNCOMMON, ItemID.JADE_NECKLACE, -1),
	POT_LID("Pot lid", Rarity.UNCOMMON, ItemID.POTLID, -1),
	DRIFT_NET("Drift net", Rarity.UNCOMMON, ItemID.FOSSIL_DRIFT_NET, -1),
	OIL_LANTERN("Oil lantern", Rarity.UNCOMMON, ItemID.OIL_LANTERN_EMPTY, -1),
	CUT_EMERALD("Cut emerald", Rarity.UNCOMMON, ItemID.EMERALD, -1),
	EMERALD_RING("Emerald ring", Rarity.UNCOMMON, ItemID.EMERALD_RING, -1),
	OPAL_AMULET("Opal amulet", Rarity.UNCOMMON, ItemID.STRUNG_OPAL_AMULET, -1),
	HARD_LEATHER_BODY("Hard leather body", Rarity.UNCOMMON, ItemID.HARDLEATHER_BODY, -1),
	EMERALD_NECKLACE("Emerald necklace", Rarity.UNCOMMON, ItemID.EMERALD_NECKLACE, -1),
	JADE_BRACELET("Jade bracelet", Rarity.UNCOMMON, ItemID.JADE_BRACELET, -1),
	EMERALD_BRACELET("Emerald bracelet", Rarity.UNCOMMON, ItemID.JEWL_EMERALD_BRACELET, -1),
	SPIN_YAK_HAIR_INTO_ROPE("Spin yak hair into rope", Rarity.UNCOMMON, ItemID.ROPE, -1),
	EMERALD_AMULET("Emerald amulet", Rarity.UNCOMMON, ItemID.STRUNG_EMERALD_AMULET, -1),
	RED_TOPAZ_NECKLACE("Red topaz necklace", Rarity.UNCOMMON, ItemID.TOPAZ_NECKLACE, -1),
	SPIKED_VAMBRACES("Spiked vambraces", Rarity.UNCOMMON, ItemID.SPIKED_VAMBRACES, -1),
	VIAL("Vial", Rarity.UNCOMMON, ItemID.VIAL_EMPTY, -1),
	CUT_RUBY("Cut ruby", Rarity.UNCOMMON, ItemID.RUBY, -1),
	JADE_AMULET("Jade amulet", Rarity.UNCOMMON, ItemID.STRUNG_JADE_AMULET, -1),
	RUBY_RING("Ruby ring", Rarity.UNCOMMON, ItemID.RUBY_RING, -1),
	BONE_STAFF("Bone staff", Rarity.UNCOMMON, ItemID.RAT_BONE_STAFF, -1),
	BROODOO_SHIELD("Broodoo shield", Rarity.UNCOMMON, ItemID.BROODOO_COMBATSHIELD_10, -1),
	CRAFT_A_BIRDHOUSE_TRAP_FROM_TEAK_LOGS("Craft a birdhouse trap from teak logs", Rarity.UNCOMMON, ItemID.BIRDHOUSE_TEAK, -1),
	CRAFT_SMALL_HUNTERS_POUCHES("Craft small hunters' pouches", Rarity.UNCOMMON, ItemID.HG_FURPOUCH_SMALL, -1),
	FRUIT_BASKET("Fruit basket", Rarity.UNCOMMON, ItemID.BASKET_EMPTY, -1),
	RABBIT_FOOT_NECKLACES("Rabbit-foot necklaces", Rarity.UNCOMMON, ItemID.HUNTING_STRUNG_RABBIT_FOOT, -1),
	COIF("Coif", Rarity.UNCOMMON, ItemID.COIF, -1),
	DENSE_ESSENCE("Dense essence", Rarity.UNCOMMON, ItemID.ARCEUUS_ESSENCE_BLOCK, -1),
	RED_TOPAZ_BRACELET("Red topaz bracelet", Rarity.UNCOMMON, ItemID.TOPAZ_BRACELET, -1),
	BOLT_OF_CANVAS("Bolt of canvas", Rarity.UNCOMMON, ItemID.BOLT_OF_CANVAS, -1),
	CRAFT_A_GEM_SATCHEL("Craft a gem satchel", Rarity.UNCOMMON, ItemID.GEM_SATCHEL, -1),
	SPIN_HEMP_INTO_HEMP_YARN("Spin hemp into hemp yarn", Rarity.UNCOMMON, ItemID.HEMP_YARN, -1),
	RUBY_NECKLACE("Ruby necklace", Rarity.RARE, ItemID.RUBY_NECKLACE, -1),
	HARD_LEATHER_SHIELD("Hard leather shield", Rarity.RARE, ItemID.LEATHER_SHIELD, -1),
	STUDDED_BODY("Studded body", Rarity.RARE, ItemID.STUDDED_BODY, -1),
	FISHBOWL("Fishbowl", Rarity.RARE, ItemID.FISHBOWL_EMPTY, -1),
	GOLD_TIARA("Gold Tiara", Rarity.RARE, ItemID.TIARA_GOLD, -1),
	RUBY_BRACELET("Ruby bracelet", Rarity.RARE, ItemID.JEWL_RUBY_BRACELET, -1),
	CUT_DIAMOND("Cut diamond", Rarity.RARE, ItemID.DIAMOND, -1),
	DIAMOND_RING("Diamond ring", Rarity.RARE, ItemID.DIAMOND_RING, -1),
	YAK_HIDE_LEG_ARMOUR("Yak-hide leg armour", Rarity.RARE, ItemID.YAK_HIDE_ARMOUR_GREAVES, -1),
	STUDDED_CHAPS("Studded chaps", Rarity.RARE, ItemID.STUDDED_CHAPS, -1),
	CRAFT_A_BIRDHOUSE_TRAP_FROM_MAPLE_LOGS("Craft a birdhouse trap from maple logs", Rarity.RARE, ItemID.BIRDHOUSE_MAPLE, -1),
	RED_TOPAZ_AMULET("Red topaz amulet", Rarity.RARE, ItemID.STRUNG_TOPAZ_AMULET, -1),
	SNAKESKIN_BOOTS("Snakeskin boots", Rarity.RARE, ItemID.SNAKESKIN_BOOTS, -1),
	GLASS_ORB("Glass orb", Rarity.RARE, ItemID.STAFFORB, -1),
	YAK_HIDE_BODY_ARMOUR("Yak-hide body armour", Rarity.RARE, ItemID.YAK_HIDE_ARMOUR_BODY, -1),
	SNAKESKIN_VAMBRACES("Snakeskin vambraces", Rarity.RARE, ItemID.SNAKESKIN_VAMBRACES, -1),
	SNAKESKIN_BANDANA("Snakeskin bandana", Rarity.RARE, ItemID.SNAKESKIN_BANDANA, -1),
	BULLSEYE_LANTERN_LENS("Bullseye lantern lens", Rarity.RARE, ItemID.BULLSEYE_LANTERN_LENS, -1),
	CLOTHES_POUCH("Clothes Pouch", Rarity.RARE, ItemID.FORESTRY_CLOTHES_POUCH, -1),
	CRAFT_A_BIRDHOUSE_TRAP_FROM_MAHOGANY_LOGS("Craft a birdhouse trap from mahogany logs", Rarity.RARE, ItemID.BIRDHOUSE_MAHOGANY, -1),
	CRAFT_MEDIUM_HUNTERS_POUCHES("Craft medium hunters' pouches", Rarity.RARE, ItemID.HG_FURPOUCH_MED, -1),
	RUBY_AMULET("Ruby amulet", Rarity.RARE, ItemID.STRUNG_RUBY_AMULET, -1),
	CRAFT_A_KNIFE_FROM_A_NARWHAL_HORN("Craft a knife from a narwhal horn", Rarity.RARE, ItemID.NARWHAL_HORN_KNIFE, -1),
	SNAKESKIN_CHAPS("Snakeskin chaps", Rarity.RARE, ItemID.SNAKESKIN_CHAPS, -1),
	SERPENTINE_HELM("Serpentine helm", Rarity.RARE, ItemID.SERPENTINE_HELM_CHARGED, -1),
	SNAKESKIN_BODY("Snakeskin body", Rarity.RARE, ItemID.SNAKESKIN_BODY, -1),
	WATER_BATTLESTAFF("Water battlestaff", Rarity.RARE, ItemID.WATER_BATTLESTAFF, -1),
	CUT_DRAGONSTONE("Cut dragonstone", Rarity.RARE, ItemID.DRAGONSTONE, -1),
	DRAGONSTONE_RING("Dragonstone ring", Rarity.RARE, ItemID.DRAGONSTONE_RING, -1),
	SLAYER_HELM("Slayer helm", Rarity.RARE, ItemID.SLAYER_HELM, -1),
	CRAFT_A_COLOSSAL_POUCH_FROM_ESSENCE_POUCHES("Craft a colossal pouch from essence pouches", Rarity.RARE, ItemID.RCU_POUCH_COLOSSAL, -1),
	DIAMOND_NECKLACE("Diamond necklace", Rarity.RARE, ItemID.DIAMOND_NECKLACE, -1),
	SNAKESKIN_SHIELD("Snakeskin shield", Rarity.RARE, ItemID.SNAKESKIN_SHIELD, -1),
	GREEN_DRAGONHIDE_VAMBRACES("Green dragonhide vambraces", Rarity.RARE, ItemID.DRAGON_VAMBRACES, -1),
	DIAMOND_BRACELET("Diamond bracelet", Rarity.RARE, ItemID.JEWL_DIAMOND_BRACELET, -1),
	EARTH_BATTLESTAFF("Earth battlestaff", Rarity.RARE, ItemID.EARTH_BATTLESTAFF, -1),
	TOXIC_STAFF_OF_THE_DEAD("Toxic Staff of the Dead", Rarity.RARE, ItemID.TOXIC_SOTD_CHARGED, -1),
	TRIDENT_OF_THE_SWAMP("Trident of the Swamp", Rarity.RARE, ItemID.TOXIC_TOTS_CHARGED, -1),
	CRAFT_A_SUNSTONE_GOLEM_ON_WYRMSCRAIG("Craft a Sunstone Golem on Wyrmscraig", Rarity.EPIC, 34020, -1),
	CRAFT_A_BIRDHOUSE_TRAP_FROM_YEW_LOGS("Craft a birdhouse trap from yew logs", Rarity.EPIC, ItemID.BIRDHOUSE_YEW, -1),
	GREEN_DRAGONHIDE_CHAPS("Green dragonhide chaps", Rarity.EPIC, ItemID.DRAGONHIDE_CHAPS, -1),
	SPLITBARK_BOOTS("Splitbark boots", Rarity.EPIC, ItemID.SPLITBARK_GREAVES, -1),
	SPLITBARK_GAUNTLETS("Splitbark gauntlets", Rarity.EPIC, ItemID.SPLITBARK_GAUNTLETS, -1),
	SPLITBARK_HELM("Splitbark helm", Rarity.EPIC, ItemID.SPLITBARK_HELM, -1),
	CRAFT_A_CRATE_FROM_CAMPHOR_LOGS("Craft a crate from camphor logs", Rarity.EPIC, ItemID.CAMPHOR_CRATE, -1),
	FIRE_BATTLESTAFF("Fire battlestaff", Rarity.EPIC, ItemID.FIRE_BATTLESTAFF, -1),
	GREEN_DRAGONHIDE_SHIELD("Green dragonhide shield", Rarity.EPIC, ItemID.GREEN_DHIDE_SHIELD, -1),
	SPLITBARK_BODY("Splitbark body", Rarity.EPIC, ItemID.SPLITBARK_BODY, -1),
	SPLITBARK_LEGS("Splitbark legs", Rarity.EPIC, ItemID.SPLITBARK_LEGS, -1),
	GREEN_DRAGONHIDE_BODY("Green dragonhide body", Rarity.EPIC, ItemID.DRAGONHIDE_BODY, -1),
	CRAFT_LARGE_HUNTERS_POUCHES("Craft large hunters' pouches", Rarity.EPIC, ItemID.HG_FURPOUCH_LARGE, -1),
	AIR_BATTLESTAFF("Air battlestaff", Rarity.EPIC, ItemID.AIR_BATTLESTAFF, -1),
	BLUE_DRAGONHIDE_VAMBRACES("Blue dragonhide vambraces", Rarity.EPIC, ItemID.BLUE_DRAGON_VAMBRACES, -1),
	CUT_ONYX("Cut onyx", Rarity.EPIC, ItemID.ONYX, -1),
	ONYX_RING("Onyx ring", Rarity.EPIC, ItemID.ONYX_RING, -1),
	BLUE_DRAGONHIDE_CHAPS("Blue dragonhide chaps", Rarity.EPIC, ItemID.BLUE_DRAGONHIDE_CHAPS, -1),
	MIXED_HIDE_CAPE("Mixed hide cape", Rarity.EPIC, ItemID.HIDE_CAPE, -1),
	BLUE_DRAGONHIDE_SHIELD("Blue dragonhide shield", Rarity.EPIC, ItemID.BLUE_DHIDE_SHIELD, -1),
	MIXED_HIDE_BOOTS("Mixed hide boots", Rarity.EPIC, ItemID.HIDE_BOOTS, -1),
	CELESTIAL_SIGNET("Celestial signet", Rarity.EPIC, ItemID.CELESTIAL_SIGNET_CHARGED, -1),
	CRYSTAL_HELM("Crystal helm", Rarity.EPIC, ItemID.CRYSTAL_HELMET, -1),
	DIAMOND_AMULET("Diamond amulet", Rarity.EPIC, ItemID.STRUNG_DIAMOND_AMULET, -1),
	BLUE_DRAGONHIDE_BODY("Blue dragonhide body", Rarity.EPIC, ItemID.BLUE_DRAGONHIDE_BODY, -1),
	MIXED_HIDE_LEGS("Mixed hide legs", Rarity.EPIC, ItemID.HIDE_LEGS, -1),
	CRYSTAL_LEGS("Crystal legs", Rarity.EPIC, ItemID.CRYSTAL_PLATELEGS, -1),
	DRAGONSTONE_NECKLACE("Dragonstone necklace", Rarity.EPIC, ItemID.DRAGONSTONE_NECKLACE, -1),
	MIXED_HIDE_BODY("Mixed hide body", Rarity.EPIC, ItemID.HIDE_TOP, -1),
	NOXIOUS_HALBERD("Noxious Halberd", Rarity.EPIC, ItemID.NOXIOUS_HALBERD, -1),
	BOLT_OF_COTTON("Bolt of cotton", Rarity.EPIC, ItemID.BOLT_OF_COTTON, -1),
	RED_DRAGONHIDE_VAMBRACES("Red dragonhide vambraces", Rarity.EPIC, ItemID.RED_DRAGON_VAMBRACES, -1),
	SPIN_COTTON_BOLL_INTO_COTTON_YARN("Spin cotton boll into cotton yarn", Rarity.EPIC, ItemID.COTTON_YARN, -1),
	CRYSTAL_BODY("Crystal body", Rarity.EPIC, ItemID.CRYSTAL_CHESTPLATE, -1),
	DRAGONSTONE_BRACELET("Dragonstone bracelet", Rarity.EPIC, ItemID.JEWL_DRAGONSTONE_BRACELET, -1),
	PURGING_STAFF("Purging staff", Rarity.EPIC, ItemID.PURGING_STAFF, -1),
	CRAFT_A_BIRDHOUSE_TRAP_FROM_MAGIC_LOGS("Craft a birdhouse trap from magic logs", Rarity.EPIC, ItemID.BIRDHOUSE_MAGIC, -1),
	CRAFT_A_DIVINE_RUNE_POUCH_FROM_A_THREAD_OF_ELIDINIS("Craft a divine rune pouch from a Thread of Elidinis", Rarity.EPIC, ItemID.DIVINE_RUNE_POUCH, -1),
	RED_DRAGONHIDE_CHAPS("Red dragonhide chaps", Rarity.EPIC, ItemID.RED_DRAGONHIDE_CHAPS, -1),
	SLAYER_RING("Slayer ring", Rarity.EPIC, ItemID.SLAYER_RING_8, -1),
	CRYSTAL_AXE("Crystal axe", Rarity.EPIC, ItemID.CRYSTAL_AXE, -1),
	CRYSTAL_FELLING_AXE("Crystal felling axe", Rarity.EPIC, ItemID.CRYSTAL_AXE_2H, -1),
	CRYSTAL_HARPOON("Crystal harpoon", Rarity.EPIC, ItemID.CRYSTAL_HARPOON, -1),
	CRYSTAL_PICKAXE("Crystal pickaxe", Rarity.EPIC, ItemID.CRYSTAL_PICKAXE, -1),
	HUEYCOATL_HIDE_COIF("Hueycoatl hide coif", Rarity.EPIC, ItemID.HUEY_COIF, -1),
	HUEYCOATL_HIDE_VAMBRACES("Hueycoatl hide vambraces", Rarity.EPIC, ItemID.HUEY_VAMBRACES, -1),
	RED_DRAGONHIDE_SHIELD("Red dragonhide shield", Rarity.EPIC, ItemID.RED_DHIDE_SHIELD, -1),
	HUEYCOATL_HIDE_CHAPS("Hueycoatl hide chaps", Rarity.EPIC, ItemID.HUEY_CHAPS, -1),
	RED_DRAGONHIDE_BODY("Red dragonhide body", Rarity.EPIC, ItemID.RED_DRAGONHIDE_BODY, -1),
	CRYSTAL_BOW("Crystal bow", Rarity.EPIC, ItemID.CRYSTAL_BOW, -1),
	CRYSTAL_HALBERD("Crystal halberd", Rarity.EPIC, ItemID.CRYSTAL_HALBERD, -1),
	CRYSTAL_SHIELD("Crystal shield", Rarity.EPIC, ItemID.CRYSTAL_SHIELD, -1),
	HUEYCOATL_HIDE_BODY("Hueycoatl hide body", Rarity.EPIC, ItemID.HUEY_BODY, -1),
	BLACK_DRAGONHIDE_VAMBRACES("Black dragonhide vambraces", Rarity.EPIC, ItemID.BLACK_DRAGON_VAMBRACES, -1),
	DRAGONSTONE_AMULET("Dragonstone amulet", Rarity.LEGENDARY, ItemID.STRUNG_DRAGONSTONE_AMULET, -1),
	ENHANCED_CRYSTAL_KEY("Enhanced crystal key", Rarity.LEGENDARY, ItemID.PRIF_CRYSTAL_KEY, -1),
	ETERNAL_TELEPORT_CRYSTAL("Eternal teleport crystal", Rarity.LEGENDARY, ItemID.PRIF_TELEPORT_CRYSTAL, -1),
	ULTOR_VENATOR_BELLATOR_MAGUS_RINGS("Ultor, Venator, Bellator, Magus rings", Rarity.LEGENDARY, ItemID.ULTOR_RING, -1),
	CRAFT_A_GEM_SACK("Craft a gem sack", Rarity.LEGENDARY, ItemID.GEM_SACK, -1),
	CRAFT_A_GEM_TOTE("Craft a gem tote", Rarity.LEGENDARY, ItemID.GEM_TOTE, -1),
	BLACK_DRAGONHIDE_CHAPS("Black dragonhide chaps", Rarity.LEGENDARY, ItemID.BLACK_DRAGONHIDE_CHAPS, -1),
	BLADE_OF_SAELDOR("Blade of Saeldor", Rarity.LEGENDARY, ItemID.BLADE_OF_SAELDOR, -1),
	BOW_OF_FAERDHINEN("Bow of Faerdhinen", Rarity.LEGENDARY, ItemID.BOW_OF_FAERDHINEN, -1),
	ONYX_NECKLACE("Onyx necklace", Rarity.LEGENDARY, ItemID.ONYX_NECKLACE, -1),
	AMETHYST_BOLT_TIPS("Amethyst bolt tips", Rarity.LEGENDARY, ItemID.BARROWS_INTERFACE_KARIL_GREEN, -1),
	BLACK_DRAGONHIDE_SHIELD("Black dragonhide shield", Rarity.LEGENDARY, ItemID.BLACK_DHIDE_SHIELD, -1),
	CONFLICTION_GAUNTLETS("Confliction gauntlets", Rarity.LEGENDARY, ItemID.CONFLICTION_GAUNTLETS, -1),
	BLACK_DRAGONHIDE_BODY("Black dragonhide body", Rarity.LEGENDARY, ItemID.BLACK_DRAGONHIDE_BODY, -1),
	NECKLACE_OF_RUPTURE("Necklace of Rupture", Rarity.LEGENDARY, ItemID.NECKLACE_OF_RUPTURE, -1),
	ONYX_BRACELET("Onyx bracelet", Rarity.LEGENDARY, ItemID.JEWL_ONYX_BRACELET, -1),
	ACCURSED_SCEPTRE("Accursed Sceptre", Rarity.LEGENDARY, ItemID.WILD_CAVE_ACCURSED_CHARGED, -1),
	AMETHYST_ARROWTIPS("Amethyst arrowtips", Rarity.LEGENDARY, ItemID.AMETHYST_ARROWHEADS, -1),
	AMULET_OF_RANCOUR("Amulet of Rancour", Rarity.LEGENDARY, ItemID.AMULET_OF_RANCOUR, -1),
	AMETHYST_JAVELIN_TIPS("Amethyst javelin tips", Rarity.LEGENDARY, ItemID.WWF_FARMING_HELPER, -1),
	DORGESHUUN_LIGHT_ORB("Dorgeshuun light orb", Rarity.LEGENDARY, ItemID.DORGESH_LIGHT_BULB, -1),
	AMETHYST_DART_TIPS("Amethyst dart tips", Rarity.LEGENDARY, ItemID.AMETHYST_DART_TIP, -1),
	CUT_ZENYTE("Cut zenyte", Rarity.LEGENDARY, ItemID.ZENYTE, -1),
	ZENYTE_RING("Zenyte ring", Rarity.LEGENDARY, ItemID.ZENYTE_RING, -1),
	CRAFT_A_BIRDHOUSE_TRAP_FROM_REDWOOD_LOGS("Craft a birdhouse trap from redwood logs", Rarity.LEGENDARY, ItemID.BIRDHOUSE_REDWOOD, -1),
	ONYX_AMULET("Onyx amulet", Rarity.LEGENDARY, ItemID.STRUNG_ONYX_AMULET, -1),
	ZENYTE_NECKLACE("Zenyte necklace", Rarity.LEGENDARY, ItemID.ZENYTE_NECKLACE, -1),
	ZENYTE_BRACELET("Zenyte bracelet", Rarity.LEGENDARY, ItemID.ZENYTE_BRACELET, -1),
	ZENYTE_AMULET("Zenyte amulet", Rarity.LEGENDARY, ItemID.ZENYTE_AMULET, -1),
	SKILLCAPE("Skillcape", Rarity.LEGENDARY, ItemID.SKILLCAPE_CRAFTING, -1);

	private final Card card;

	CraftingCards(String name, Rarity rarity, int itemId, int spriteId)
	{
		this.card = CardGroup.build(CardSet.CRAFTING, name, rarity, itemId, spriteId);
	}

	@Override
	public Card getCard()
	{
		return card;
	}
}
