/*
 * Copyright (c) 2026, Zoinkwiz <https://github.com/Zoinkwiz>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package com.dopaminesimulator.cards.sets;

import com.dopaminesimulator.cards.Card;
import com.dopaminesimulator.cards.CardGroup;
import com.dopaminesimulator.cards.CardSet;
import com.dopaminesimulator.cards.Rarity;
import net.runelite.api.gameval.ItemID;
import net.runelite.api.gameval.SpriteID;

public enum QuestsCards implements CardGroup
{
	BELOW_ICE_MOUNTAIN("Below Ice Mountain", Rarity.COMMON, ItemID.BIM_STEAK_SANDWICH, -1),
	BIOHAZARD("Biohazard", Rarity.COMMON, ItemID.DISTILLATOR, -1),
	CLIENT_OF_KOUREND("Client of Kourend", Rarity.COMMON, ItemID.VEOS_KHAREDSTS_MEMOIRS, -1),
	CLOCK_TOWER("Clock Tower", Rarity.COMMON, ItemID.BLACKCOG, -1),
	COOK_S_ASSISTANT("Cook's Assistant", Rarity.COMMON, ItemID.CAKE, -1),
	DEATH_PLATEAU("Death Plateau", Rarity.COMMON, ItemID.DEATH_CLIMBINGBOOTS, -1),
	DEMON_SLAYER("Demon Slayer", Rarity.COMMON, ItemID.SILVERLIGHT, -1),
	DORIC_S_QUEST("Doric's Quest", Rarity.COMMON, ItemID.COPPER_ORE, -1),
	DRUIDIC_RITUAL("Druidic Ritual", Rarity.COMMON, ItemID.GUAM_LEAF, -1),
	DWARF_CANNON("Dwarf Cannon", Rarity.COMMON, ItemID.MCANNONTOOLKIT, -1),
	EAGLES_PEAK("Eagles' Peak", Rarity.COMMON, ItemID.HUNTING_FERRET, -1),
	ELEMENTAL_WORKSHOP_I("Elemental Workshop I", Rarity.COMMON, ItemID.ELEMENTAL_SHIELD, -1),
	ERNEST_THE_CHICKEN("Ernest the Chicken", Rarity.COMMON, ItemID.RAW_CHICKEN, -1),
	FISHING_CONTEST("Fishing Contest", Rarity.COMMON, ItemID.HEMENSTER_FISHING_TROPHY, -1),
	GERTRUDE_S_CAT("Gertrude's Cat", Rarity.COMMON, ItemID.LAZYCATOBJECT_BROWN, -1),
	GOBLIN_DIPLOMACY("Goblin Diplomacy", Rarity.COMMON, ItemID.GOBLIN_ARMOUR, -1),
	HAZEEL_CULT("Hazeel Cult", Rarity.COMMON, ItemID.CARNILLEAN_ARMOUR, -1),
	IMP_CATCHER("Imp Catcher", Rarity.COMMON, ItemID.AMULET_OF_ACCURACY, -1),
	JUNGLE_POTION("Jungle Potion", Rarity.COMMON, ItemID.SNAKE_WEED, -1),
	MISTHALIN_MYSTERY("Misthalin Mystery", Rarity.COMMON, ItemID.MACRO_QUIZ_MYSTERY_BOX, -1),
	MONK_S_FRIEND("Monk's Friend", Rarity.COMMON, ItemID.MONKROBETOP, -1),
	MURDER_MYSTERY("Murder Mystery", Rarity.COMMON, ItemID.MURDERNECKLACE, -1),
	PIRATE_S_TREASURE("Pirate's Treasure", Rarity.COMMON, ItemID.CASKET, -1),
	PLAGUE_CITY("Plague City", Rarity.COMMON, ItemID.GASMASK, -1),
	A_PORCINE_OF_INTEREST("A Porcine of Interest", Rarity.COMMON, ItemID.PORCINE_SOURHOG_TROPHY, -1),
	PRIEST_IN_PERIL("Priest in Peril", Rarity.COMMON, ItemID.DAGGER_WOLFBANE, -1),
	PRINCE_ALI_RESCUE("Prince Ali Rescue", Rarity.COMMON, ItemID.SKINPASTE, -1),
	RAG_AND_BONE_MAN_I("Rag and Bone Man I", Rarity.COMMON, ItemID.RAG_POLISHED_GOBLIN_BONE, -1),
	RECRUITMENT_DRIVE("Recruitment Drive", Rarity.COMMON, ItemID.BASIC_TK_HELM, -1),
	THE_RESTLESS_GHOST("The Restless Ghost", Rarity.COMMON, ItemID.AMULET_OF_GHOSTSPEAK, -1),
	ROMEO_JULIET("Romeo & Juliet", Rarity.COMMON, ItemID.CADAVA, -1),
	RUNE_MYSTERIES("Rune Mysteries", Rarity.COMMON, ItemID.AIR_TALISMAN, -1),
	SHEEP_HERDER("Sheep Herder", Rarity.COMMON, ItemID.PLAGUE_JACKET, -1),
	SHEEP_SHEARER("Sheep Shearer", Rarity.COMMON, ItemID.BALL_OF_WOOL, -1),
	SHIELD_OF_ARRAV("Shield of Arrav", Rarity.COMMON, ItemID.THE_SHIELD_OF_ARRAV, -1),
	TOWER_OF_LIFE("Tower of Life", Rarity.COMMON, ItemID.TOL_PLAYER_CONSTRUCTION_HARDHAT, -1),
	WITCH_S_POTION("Witch's Potion", Rarity.COMMON, ItemID.EYE_OF_NEWT, -1),
	X_MARKS_THE_SPOT("X Marks the Spot", Rarity.COMMON, ItemID.SPADE, -1),
	RECIPE_FOR_DISASTER_ANOTHER_COOK_S_QUEST("Recipe for Disaster - Another Cook's Quest", Rarity.COMMON, ItemID.EGG, -1),
	CHILDREN_OF_THE_SUN("Children of the Sun", Rarity.COMMON, ItemID.VARLAMORE_JAGUAR_FUR, -1),
	AT_FIRST_LIGHT("At First Light", Rarity.COMMON, ItemID.GB_MOSS_ESSENCE, -1),
	THE_RIBBITING_TALE_OF_A_LILY_PAD_LABOUR_DISPUTE("The Ribbiting Tale of a Lily Pad Labour Dispute", Rarity.COMMON, ItemID.ORANGE, -1),
	ETHICALLY_ACQUIRED_ANTIQUITIES("Ethically Acquired Antiquities", Rarity.COMMON, ItemID.VM_MUSEUM_MAP, -1),
	PANDEMONIUM("Pandemonium", Rarity.COMMON, ItemID.SAILING_CHARTING_SPYGLASS, -1),
	CURRENT_AFFAIRS("Current Affairs", Rarity.COMMON, ItemID.DUMMY_CHARTING_DUCK, -1),
	LEARNING_THE_ROPES("Learning the Ropes", Rarity.COMMON, ItemID.BURNT_SHRIMP, -1),
	THE_IDES_OF_MILK("The Ides of Milk", Rarity.COMMON, ItemID.COWQUEST_MILK_SAMPLE_1, -1),
	ANIMAL_MAGNETISM("Animal Magnetism", Rarity.UNCOMMON, ItemID.AVAS_ASSEMBLER, -1),
	ANOTHER_SLICE_OF_H_A_M("Another Slice of H.A.M.", Rarity.UNCOMMON, ItemID.ANCIENT_GOBLIN_MACE, -1),
	THE_ASCENT_OF_ARCEUUS("The Ascent of Arceuus", Rarity.UNCOMMON, ItemID.ARCEUUS_ESSENCE_BLOCK_DARK, -1),
	ALFRED_GRIMHAND_S_BARCRAWL("Alfred Grimhand's Barcrawl", Rarity.UNCOMMON, ItemID.BARCRAWL_CARD, -1),
	BEAR_YOUR_SOUL("Bear Your Soul", Rarity.UNCOMMON, ItemID.ARCEUUS_SOULBEARER, -1),
	BIG_CHOMPY_BIRD_HUNTING("Big Chompy Bird Hunting", Rarity.UNCOMMON, ItemID.OGRE_BOW, -1),
	BLACK_KNIGHTS_FORTRESS("Black Knights' Fortress", Rarity.UNCOMMON, ItemID.IRON_CHAINBODY, -1),
	BONE_VOYAGE("Bone Voyage", Rarity.UNCOMMON, ItemID.FOSSIL_CALCITE, -1),
	COLD_WAR("Cold War", Rarity.UNCOMMON, ItemID.PENGUIN_MASK, -1),
	THE_CORSAIR_CURSE("The Corsair Curse", Rarity.UNCOMMON, ItemID.PIRATE_BANDANA_BROWN, -1),
	CREATURE_OF_FENKENSTRAIN("Creature of Fenkenstrain", Rarity.UNCOMMON, ItemID.RING_OF_CHAROS, -1),
	CURSE_OF_THE_EMPTY_LORD("Curse of the Empty Lord", Rarity.UNCOMMON, ItemID.SECRET_GHOST_TOP, -1),
	DADDY_S_HOME("Daddy's Home", Rarity.UNCOMMON, ItemID.POH_SAW, -1),
	DEATH_TO_THE_DORGESHUUN("Death to the Dorgeshuun", Rarity.UNCOMMON, ItemID.DTTD_BONE_CROSSBOW, -1),
	THE_DEPTHS_OF_DESPAIR("The Depths of Despair", Rarity.UNCOMMON, ItemID.HOSIDIUSQUEST_ACCORD, -1),
	THE_DIG_SITE("The Dig Site", Rarity.UNCOMMON, ItemID.SPECIMEN_BRUSH, -1),
	EADGAR_S_RUSE("Eadgar's Ruse", Rarity.UNCOMMON, ItemID.EADGAR_GOUTWEED_HERB, -1),
	ELEMENTAL_WORKSHOP_II("Elemental Workshop II", Rarity.UNCOMMON, ItemID.ELEM_MIND_HELM, -1),
	THE_ENCHANTED_KEY("The Enchanted Key", Rarity.UNCOMMON, ItemID.MAKINGHISTORY_KEY, -1),
	ENLIGHTENED_JOURNEY("Enlightened Journey", Rarity.UNCOMMON, ItemID.ZEP_TEST_BALLOON, -1),
	ENTER_THE_ABYSS("Enter the Abyss", Rarity.UNCOMMON, ItemID.RCU_POUCH_SMALL, -1),
	THE_EYES_OF_GLOUPHRIE("The Eyes of Glouphrie", Rarity.UNCOMMON, ItemID.EYEGLO_BLUE_CIRCLE, -1),
	FAIRYTALE_I_GROWING_PAINS("Fairytale I - Growing Pains", Rarity.UNCOMMON, ItemID.FAIRY_ENCHANTED_SECATEURS, -1),
	FAMILY_PEST("Family Pest", Rarity.UNCOMMON, ItemID.GAUNTLETS_OF_CHAOS, -1),
	THE_FEUD("The Feud", Rarity.UNCOMMON, ItemID.BLACKJACK_OAK, -1),
	FIGHT_ARENA("Fight Arena", Rarity.UNCOMMON, ItemID.KHAZARD_PLATEMAIL, -1),
	FORGETTABLE_TALE("Forgettable Tale...", Rarity.UNCOMMON, ItemID.DWARVEN_STOUT, -1),
	THE_FORSAKEN_TOWER("The Forsaken Tower", Rarity.UNCOMMON, ItemID.LOVAQUEST_HAMMER, -1),
	THE_FREMENNIK_TRIALS("The Fremennik Trials", Rarity.UNCOMMON, ItemID.VIKING_ENCHANTED_STRUNG_LYRE, -1),
	GARDEN_OF_TRANQUILLITY("Garden of Tranquillity", Rarity.UNCOMMON, ItemID.RING_OF_CHAROS_UNLOCKED, -1),
	THE_GENERAL_S_SHADOW("The General's Shadow", Rarity.UNCOMMON, ItemID.SHADOW_MAJ_SHADOW_SWORD, -1),
	GETTING_AHEAD("Getting Ahead", Rarity.UNCOMMON, ItemID.GA_FURHEAD, -1),
	GHOSTS_AHOY("Ghosts Ahoy", Rarity.UNCOMMON, ItemID.ECTOPHIAL, -1),
	THE_GIANT_DWARF("The Giant Dwarf", Rarity.UNCOMMON, ItemID.POH_UNFRAMED_PAINTING_GIANTDWARF, -1),
	THE_GOLEM("The Golem", Rarity.UNCOMMON, ItemID.GOLEM_STATUETTE, -1),
	THE_GRAND_TREE("The Grand Tree", Rarity.UNCOMMON, ItemID.GRANDTREE_DACONIAROCK, -1),
	THE_HAND_IN_THE_SAND("The Hand in the Sand", Rarity.UNCOMMON, ItemID.HANDSAND_SANDYHAND, -1),
	HOLY_GRAIL("Holy Grail", Rarity.UNCOMMON, ItemID.HOLY_GRAIL, -1),
	HORROR_FROM_THE_DEEP("Horror from the Deep", Rarity.UNCOMMON, ItemID.HORROR_CASKET, -1),
	ICTHLARIN_S_LITTLE_HELPER("Icthlarin's Little Helper", Rarity.UNCOMMON, ItemID.ICS_LITTLE_AMULET_OF_CATSPEAK, -1),
	IN_AID_OF_THE_MYREQUE("In Aid of the Myreque", Rarity.UNCOMMON, ItemID.BURGH_ROD_COMMAND_FINAL_10, -1),
	IN_SEARCH_OF_KNOWLEDGE("In Search of Knowledge", Rarity.UNCOMMON, ItemID.ARCEUUS_LIBRARY_REWARD, -1),
	IN_SEARCH_OF_THE_MYREQUE("In Search of the Myreque", Rarity.UNCOMMON, ItemID.SILVER_SICKLE, -1),
	THE_KNIGHT_S_SWORD("The Knight's Sword", Rarity.UNCOMMON, ItemID.FALADIAN_SWORD, -1),
	LAIR_OF_TARN_RAZORLOR("Lair of Tarn Razorlor", Rarity.UNCOMMON, ItemID.LOTR_CRYSTALSHARD_NECKLACE_UPGRADE, -1),
	LOST_CITY("Lost City", Rarity.UNCOMMON, ItemID.DRAMEN_STAFF, -1),
	THE_LOST_TRIBE("The Lost Tribe", Rarity.UNCOMMON, ItemID.LOST_TRIBE_BROOCH, -1),
	MAGE_ARENA_I("Mage Arena I", Rarity.UNCOMMON, ItemID.SARADOMIN_CAPE, -1),
	MAGE_ARENA_II("Mage Arena II", Rarity.UNCOMMON, ItemID.MA2_SARADOMIN_CAPE, -1),
	MAKING_HISTORY("Making History", Rarity.UNCOMMON, ItemID.MAKINGHISTORY_KEY, -1),
	MERLIN_S_CRYSTAL("Merlin's Crystal", Rarity.UNCOMMON, ItemID.EXCALIBUR, -1),
	MOUNTAIN_DAUGHTER("Mountain Daughter", Rarity.UNCOMMON, ItemID.MDAUGHTER_BEAR_HELMET, -1),
	NATURE_SPIRIT("Nature Spirit", Rarity.UNCOMMON, ItemID.SILVER_SICKLE_BLESSED, -1),
	OBSERVATORY_QUEST("Observatory Quest", Rarity.UNCOMMON, ItemID.TELESCOPE_DUMMY, -1),
	OLAF_S_QUEST("Olaf's Quest", Rarity.UNCOMMON, ItemID.OLAF2_GATE_KEY_1, -1),
	THE_QUEEN_OF_THIEVES("The Queen of Thieves", Rarity.UNCOMMON, ItemID.VEOS_MEMOIRS_PISC_PAGE, -1),
	RATCATCHERS("Ratcatchers", Rarity.UNCOMMON, ItemID.SNAKE_FLUTE, -1),
	SCORPION_CATCHER("Scorpion Catcher", Rarity.UNCOMMON, ItemID.SCORPIONCAGEFULL, -1),
	SEA_SLUG("Sea Slug", Rarity.UNCOMMON, ItemID.SLUG2_SEASLUG_YOUNG, -1),
	SHADES_OF_MORT_TON("Shades of Mort'ton", Rarity.UNCOMMON, ItemID.FLAMTAER_HAMMER, -1),
	SHADOW_OF_THE_STORM("Shadow of the Storm", Rarity.UNCOMMON, ItemID.DARKLIGHT, -1),
	SHILO_VILLAGE("Shilo Village", Rarity.UNCOMMON, ItemID.MOSOL_WAMPUM_BELT, -1),
	SKIPPY_AND_THE_MOGRES("Skippy and the Mogres", Rarity.UNCOMMON, ItemID.SLAYERGUIDE_MOGRE, -1),
	THE_SLUG_MENACE("The Slug Menace", Rarity.UNCOMMON, ItemID.BASIC_TK_RANK2_HELM, -1),
	A_SOUL_S_BANE("A Soul's Bane", Rarity.UNCOMMON, ItemID.SOULBANE_ZAROS_SPEAR, -1),
	SPIRITS_OF_THE_ELID("Spirits of the Elid", Rarity.UNCOMMON, ItemID.ELID_STATUETTE, -1),
	TAI_BWO_WANNAI_TRIO("Tai Bwo Wannai Trio", Rarity.UNCOMMON, ItemID.TBWT_RAW_KARAMBWAN, -1),
	A_TAIL_OF_TWO_CATS("A Tail of Two Cats", Rarity.UNCOMMON, ItemID.TWOCATS_AMULETOFCATSPEAK, -1),
	TALE_OF_THE_RIGHTEOUS("Tale of the Righteous", Rarity.UNCOMMON, ItemID.SHAYZIENQUEST_CRYSTAL_DUMMY, -1),
	TEARS_OF_GUTHIX("Tears of Guthix", Rarity.UNCOMMON, ItemID.TOG_BOWL, -1),
	TEMPLE_OF_IKOV("Temple of Ikov", Rarity.UNCOMMON, ItemID.IKOV_STAFFOFARMARDYL, -1),
	THE_TOURIST_TRAP("The Tourist Trap", Rarity.UNCOMMON, ItemID.DESERT_SHIRT, -1),
	TREE_GNOME_VILLAGE("Tree Gnome Village", Rarity.UNCOMMON, ItemID.GNOME_AMULET, -1),
	TRIBAL_TOTEM("Tribal Totem", Rarity.UNCOMMON, ItemID.TRIBAL_TOTEM, -1),
	TROLL_ROMANCE("Troll Romance", Rarity.UNCOMMON, ItemID.TROLLROMANCE_TOBOGGON, -1),
	TROLL_STRONGHOLD("Troll Stronghold", Rarity.UNCOMMON, ItemID.TROLL_KEY_PRISON, -1),
	VAMPYRE_SLAYER("Vampyre Slayer", Rarity.UNCOMMON, ItemID.STAKE, -1),
	WANTED("Wanted!", Rarity.UNCOMMON, ItemID.WANTED_SOLUS_TROPHY, -1),
	WATCHTOWER("Watchtower", Rarity.UNCOMMON, ItemID.OGRERELIC, -1),
	WATERFALL_QUEST("Waterfall Quest", Rarity.UNCOMMON, ItemID.GLARIALS_AMULET_WATERFALL_QUEST, -1),
	WHAT_LIES_BELOW("What Lies Below", Rarity.UNCOMMON, ItemID.SUROK_RING, -1),
	WITCH_S_HOUSE("Witch's House", Rarity.UNCOMMON, ItemID.BALL, -1),
	ZOGRE_FLESH_EATERS("Zogre Flesh Eaters", Rarity.UNCOMMON, ItemID.ZOGRE_BOW, -1),
	THE_FROZEN_DOOR("The Frozen Door", Rarity.UNCOMMON, ItemID.NEX_FROZEN_KEY, -1),
	HOPESPEAR_S_WILL("Hopespear's Will", Rarity.UNCOMMON, ItemID.LOTG_BONE_HIGHPRIEST5, -1),
	TEMPLE_OF_THE_EYE("Temple of the Eye", Rarity.UNCOMMON, ItemID.TOTE_AMULET, -1),
	SLEEPING_GIANTS("Sleeping Giants", Rarity.UNCOMMON, ItemID.GIANTS_FOUNDRY_COLOSSAL_BLADE, -1),
	THE_GARDEN_OF_DEATH("The Garden of Death", Rarity.UNCOMMON, ItemID.TGOD_TABLET_1, -1),
	INTO_THE_TOMBS("Into the Tombs", Rarity.UNCOMMON, ItemID.OSMUMTENS_FANG, -1),
	RECIPE_FOR_DISASTER_MOUNTAIN_DWARF("Recipe for Disaster - Mountain Dwarf", Rarity.UNCOMMON, ItemID.ROCKCAKE, -1),
	RECIPE_FOR_DISASTER_WARTFACE_BENTNOZE("Recipe for Disaster - Wartface & Bentnoze", Rarity.UNCOMMON, ItemID._100GOBLIN_COMPROMISE_MUSH, -1),
	RECIPE_FOR_DISASTER_PIRATE_PETE("Recipe for Disaster - Pirate Pete", Rarity.UNCOMMON, ItemID.HUNDRED_PIRATE_FISHCAKE, -1),
	HIS_FAITHFUL_SERVANTS("His Faithful Servants", Rarity.UNCOMMON, ItemID.BARROWS_BOOK_HISTORY, -1),
	BARBARIAN_TRAINING("Barbarian Training", Rarity.UNCOMMON, ItemID.BRUT_FISHING_ROD, -1),
	TWILIGHT_S_PROMISE("Twilight's Promise", Rarity.UNCOMMON, ItemID.VMQ2_CREST, -1),
	DEATH_ON_THE_ISLE("Death on the Isle", Rarity.UNCOMMON, ItemID.DOTI_CASEFILE, -1),
	SCRAMBLED("Scrambled!", Rarity.UNCOMMON, ItemID.SCRAMBLED_EGG, -1),
	VALE_TOTEMS("Vale Totems", Rarity.UNCOMMON, ItemID.ENT_TOTEMS_LOOT, -1),
	PRYING_TIMES("Prying Times", Rarity.UNCOMMON, ItemID.PRYING_TIMES_CARGO_CRATE, -1),
	BETWEEN_A_ROCK("Between a Rock...", Rarity.RARE, ItemID.DWARF_GOLDROCK_HELMET, -1),
	CABIN_FEVER("Cabin Fever", Rarity.RARE, ItemID.FEVER_PIRACY_BOOK, -1),
	CONTACT("Contact!", Rarity.RARE, ItemID.CONTACT_KERIS, -1),
	DARKNESS_OF_HALLOWVALE("Darkness of Hallowvale", Rarity.RARE, ItemID.SILVER_SICKLE_ENCHANTED, -1),
	DEVIOUS_MINDS("Devious Minds", Rarity.RARE, ItemID.DEVIOUS_BOWSWORD, -1),
	DRAGON_SLAYER_I("Dragon Slayer I", Rarity.RARE, ItemID.ANTIDRAGONBREATHSHIELD, -1),
	ENAKHRA_S_LAMENT("Enakhra's Lament", Rarity.RARE, ItemID.CAMULET, -1),
	FAIRYTALE_II_CURE_A_QUEEN("Fairytale II - Cure a Queen", Rarity.RARE, ItemID.FAIRYTALE2_NUFFS_CERTIFICATE, -1),
	FAMILY_CREST("Family Crest", Rarity.RARE, ItemID.FAMILY_CREST, -1),
	THE_FREMENNIK_ISLES("The Fremennik Isles", Rarity.RARE, ItemID.FRIS_KINGLY_HELM, -1),
	THE_GREAT_BRAIN_ROBBERY("The Great Brain Robbery", Rarity.RARE, ItemID.BRAIN_ANCHOR, -1),
	HAUNTED_MINE("Haunted Mine", Rarity.RARE, ItemID.CRYSTALSHARD_NECKLACE, -1),
	HEROES_QUEST("Heroes' Quest", Rarity.RARE, ItemID.DRAGON_BATTLEAXE, -1),
	A_KINGDOM_DIVIDED("A Kingdom Divided", Rarity.RARE, ItemID.AKD_ROSES_DUMMY, -1),
	KING_S_RANSOM("King's Ransom", Rarity.RARE, ItemID.KR_CLUE_ARMOUR, -1),
	LUNAR_DIPLOMACY("Lunar Diplomacy", Rarity.RARE, ItemID.LUNAR_MOONCLAN_LIMINAL_STAFF, -1),
	MY_ARM_S_BIG_ADVENTURE("My Arm's Big Adventure", Rarity.RARE, ItemID.MYARM_HARDYTUBERS, -1),
	ONE_SMALL_FAVOUR("One Small Favour", Rarity.RARE, ItemID.FAVOUR_KEY_RING, -1),
	RAG_AND_BONE_MAN_II("Rag and Bone Man II", Rarity.RARE, ItemID.RAG_BONESACK, -1),
	REGICIDE("Regicide", Rarity.RARE, ItemID.DRAGON_HALBERD, -1),
	ROVING_ELVES("Roving Elves", Rarity.RARE, ItemID.CRYSTAL_BOW, -1),
	ROYAL_TROUBLE("Royal Trouble", Rarity.RARE, ItemID.ROYAL_BOX, -1),
	RUM_DEAL("Rum Deal", Rarity.RARE, ItemID.DEAL_WRENCH_BLESSED, -1),
	A_TASTE_OF_HOPE("A Taste of Hope", Rarity.RARE, ItemID.IVANDIS_FLAIL, -1),
	THRONE_OF_MISCELLANIA("Throne of Miscellania", Rarity.RARE, ItemID.MISC_TREATY, -1),
	UNDERGROUND_PASS("Underground Pass", Rarity.RARE, ItemID.IBANSTAFF, -1),
	LAND_OF_THE_GOBLINS("Land of the Goblins", Rarity.RARE, ItemID.LOTG_3DOSEGOBLIN, -1),
	RECIPE_FOR_DISASTER_LUMBRIDGE_GUIDE("Recipe for Disaster - Lumbridge Guide", Rarity.RARE, ItemID._100GUIDE_GUIDECAKE, -1),
	RECIPE_FOR_DISASTER_EVIL_DAVE("Recipe for Disaster - Evil Dave", Rarity.RARE, ItemID.HUNDRED_DAVE_STEW, -1),
	RECIPE_FOR_DISASTER_SKRACH_UGLOGWEE("Recipe for Disaster - Skrach Uglogwee", Rarity.RARE, ItemID._100_JUBBLY_MEAT_COOKED, -1),
	THE_PATH_OF_GLOUPHRIE("The Path of Glouphrie", Rarity.RARE, ItemID.CRYSTAL_CHIME, -1),
	DEFENDER_OF_VARROCK("Defender of Varrock", Rarity.RARE, ItemID.DOV_SHIELD_OF_ARRAV, -1),
	THE_HEART_OF_DARKNESS("The Heart of Darkness", Rarity.RARE, ItemID.VMQ3_CULTIST_ROBE_TOP, -1),
	MEAT_AND_GREET("Meat and Greet", Rarity.RARE, ItemID.COOKED_MEAT_UNDEAD, -1),
	SHADOWS_OF_CUSTODIA("Shadows of Custodia", Rarity.RARE, ItemID.CUSTODIAN_ANTLER_GUARD, -1),
	TROUBLED_TORTUGANS("Troubled Tortugans", Rarity.RARE, ItemID.TORTUGAN_SHIELD, -1),
	THE_RED_REEF("The Red Reef", Rarity.RARE, ItemID.TRR_RED_CORAL, -1),
	DESERT_TREASURE_I("Desert Treasure I", Rarity.EPIC, ItemID.TRAIL_ANCIENT_STAFF, -1),
	DREAM_MENTOR("Dream Mentor", Rarity.EPIC, ItemID.DREAM_VIAL_FULL, -1),
	THE_FREMENNIK_EXILES("The Fremennik Exiles", Rarity.EPIC, ItemID.NEITIZNOT_FACEGUARD, -1),
	GRIM_TALES("Grim Tales", Rarity.EPIC, ItemID.GRIM_WEAR_HELMET, -1),
	LEGENDS_QUEST("Legends' Quest", Rarity.EPIC, ItemID.CAPE_OF_LEGENDS, -1),
	MAKING_FRIENDS_WITH_MY_ARM("Making Friends with My Arm", Rarity.EPIC, ItemID.MY2ARM_COFFIN, -1),
	MONKEY_MADNESS_I("Monkey Madness I", Rarity.EPIC, ItemID.DRAGON_SCIMITAR, -1),
	MOURNING_S_END_PART_I("Mourning's End Part I", Rarity.EPIC, ItemID.MOURNING_MOURNER_TOP, -1),
	MOURNING_S_END_PART_II("Mourning's End Part II", Rarity.EPIC, ItemID.DEATH_TALISMAN, -1),
	A_NIGHT_AT_THE_THEATRE("A Night at the Theatre", Rarity.EPIC, ItemID.VERZIK_SPECIAL_WEAPON, -1),
	SINS_OF_THE_FATHER("Sins of the Father", Rarity.EPIC, ItemID.BLISTERWOOD_FLAIL, -1),
	SWAN_SONG("Swan Song", Rarity.EPIC, ItemID.MONKFISH, -1),
	BENEATH_CURSED_SANDS("Beneath Cursed Sands", Rarity.EPIC, ItemID.KERIS_PARTISAN, -1),
	RECIPE_FOR_DISASTER_SIR_AMIK_VARZE("Recipe for Disaster - Sir Amik Varze", Rarity.EPIC, ItemID.CHICKENQUEST_EVIL_CHICKEN_EGG, -1),
	RECIPE_FOR_DISASTER_KING_AWOWOGEI("Recipe for Disaster - King Awowogei", Rarity.EPIC, ItemID.HUNDRED_ILM_COOKED_STUFFED_SNAKE, -1),
	SECRETS_OF_THE_NORTH("Secrets of the North", Rarity.EPIC, ItemID.VENATOR_BOW, -1),
	PERILOUS_MOONS("Perilous Moons", Rarity.EPIC, ItemID.PMOON_ICOSAHEDRON, -1),
	THE_CURSE_OF_ARRAV("The Curse of Arrav", Rarity.EPIC, ItemID.COA_CANOPIC_JAR_COMPLETE, -1),
	THE_FINAL_DAWN("The Final Dawn", Rarity.EPIC, ItemID.ARKAN_BLADE, -1),
	DRAGON_SLAYER_II("Dragon Slayer II", Rarity.LEGENDARY, ItemID.MYTHICAL_CAPE, -1),
	MONKEY_MADNESS_II("Monkey Madness II", Rarity.LEGENDARY, ItemID.HEAVY_BALLISTA, -1),
	RECIPE_FOR_DISASTER("Recipe for Disaster", Rarity.LEGENDARY, ItemID.HUNDRED_GAUNTLETS_LEVEL_10, -1),
	SONG_OF_THE_ELVES("Song of the Elves", Rarity.LEGENDARY, ItemID.BLADE_OF_SAELDOR, -1),
	RECIPE_FOR_DISASTER_CULINAROMANCER("Recipe for Disaster - Culinaromancer", Rarity.LEGENDARY, ItemID.HUNDRED_GAUNTLETS_LEVEL_10, -1),
	DESERT_TREASURE_II_THE_FALLEN_EMPIRE("Desert Treasure II - The Fallen Empire", Rarity.LEGENDARY, ItemID.DT2_ELDER_HORN_DUMMY, -1),
	WHILE_GUTHIX_SLEEPS("While Guthix Sleeps", Rarity.LEGENDARY, ItemID.WGS_STONE_OF_JAS_DUMMY_ITEM, -1),
	THE_BLOOD_MOON_RISES("The Blood Moon Rises", Rarity.LEGENDARY, ItemID.HALLOWED_FLAIL, -1);

	private final Card card;

	QuestsCards(String name, Rarity rarity, int itemId, int spriteId)
	{
		this.card = CardGroup.build(CardSet.QUESTS, name, rarity, itemId, spriteId);
	}

	@Override
	public Card getCard()
	{
		return card;
	}
}
