/*
 * Copyright (c) 2026, Zoinkwiz <https://github.com/Zoinkwiz>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package com.dopaminesimulator.cards.sets;

import com.dopaminesimulator.cards.Card;
import com.dopaminesimulator.cards.CardGroup;
import com.dopaminesimulator.cards.CardSet;
import com.dopaminesimulator.cards.Rarity;
import net.runelite.api.gameval.ItemID;
import net.runelite.api.gameval.SpriteID;

public enum SailingCards implements CardGroup
{
	BRONZE_HELM("Bronze helm", Rarity.COMMON, ItemID.SAILING_SKILLGUIDE_HELM_BRONZE, -1),
	BRONZE_KEEL("Bronze keel", Rarity.COMMON, ItemID.SAILING_SKILLGUIDE_KEEL_BRONZE, -1),
	BRONZE_SALVAGING_HOOK("Bronze salvaging hook", Rarity.COMMON, ItemID.SAILING_SKILLGUIDE_SALVAGING_HOOK_BRONZE, -1),
	PORT_SARIM("Port Sarim", Rarity.COMMON, ItemID.SAILING_SKILLGUIDE_PORTS_PORT_SARIM, -1),
	RAFT("Raft", Rarity.COMMON, ItemID.SAILING_SKILLGUIDE_BOAT_HULL_RAFT_WOOD, -1),
	SPYGLASS_CHARTING("Spyglass charting", Rarity.COMMON, ItemID.SAILING_CHARTING_SPYGLASS, -1),
	THE_PANDEMONIUM("The Pandemonium", Rarity.COMMON, ItemID.SAILING_SKILLGUIDE_PORTS_THE_PANDEMONIUM, -1),
	WOODEN_CARGO_HOLD("Wooden cargo hold", Rarity.COMMON, ItemID.SAILING_SKILLGUIDE_BOAT_CARGO_HOLD_REGULAR, -1),
	WOODEN_HULL("Wooden hull", Rarity.COMMON, ItemID.SAILING_SKILLGUIDE_REGULAR_HULL, -1),
	WOODEN_HULL_HULL_PARTS("Wooden hull & hull parts", Rarity.COMMON, ItemID.SAILING_SKILLGUIDE_REGULAR_HULL, -1),
	WOODEN_MAST_AND_LINEN_SAILS("Wooden mast and linen sails", Rarity.COMMON, ItemID.SAILING_SKILLGUIDE_MAST_WOODEN, -1),
	HOSIDIUS("Hosidius", Rarity.COMMON, ItemID.SAILING_SKILLGUIDE_PORTS_HOSIDIUS, -1),
	LAND_S_END("Land's End", Rarity.COMMON, ItemID.SAILING_SKILLGUIDE_PORTS_LANDS_END, -1),
	OAK_HULL_HULL_PARTS("Oak hull & hull parts", Rarity.COMMON, ItemID.SAILING_SKILLGUIDE_OAK_HULL, -1),
	IRON_SALVAGING_HOOK("Iron salvaging hook", Rarity.COMMON, ItemID.SAILING_SKILLGUIDE_SALVAGING_HOOK_IRON, -1),
	MUSA_POINT("Musa Point", Rarity.COMMON, ItemID.SAILING_SKILLGUIDE_PORTS_MUSA_POINT, -1),
	OAK_MAST_AND_LINEN_SAILS("Oak mast and linen sails", Rarity.COMMON, ItemID.SAILING_SKILLGUIDE_MAST_OAK, -1),
	DRINK_CRATE_CHARTING("Drink crate charting", Rarity.COMMON, ItemID.SAILING_CHARTING_CROWBAR, -1),
	PORT_PISCARILLIUS("Port Piscarillius", Rarity.COMMON, ItemID.SAILING_SKILLGUIDE_PORTS_PORT_PISCARILLIUS, -1),
	SKIFF("Skiff", Rarity.COMMON, ItemID.SAILING_SKILLGUIDE_BOAT_HULL_KANDARIN_2X5_WOOD, -1),
	SMALL_SHIPWRECKS("Small shipwrecks", Rarity.COMMON, ItemID.SAILING_SMALL_SHIPWRECK_SALVAGE, -1),
	RANGE("Range", Rarity.COMMON, ItemID.SAILING_SKILLGUIDE_RANGE, -1),
	IRON_KEEL("Iron keel", Rarity.COMMON, ItemID.SAILING_SKILLGUIDE_KEEL_IRON, -1),
	OAK_CARGO_HOLD("Oak cargo hold", Rarity.COMMON, ItemID.SAILING_SKILLGUIDE_BOAT_CARGO_HOLD_OAK, -1),
	RIMMINGTON("Rimmington", Rarity.COMMON, ItemID.SAILING_SKILLGUIDE_PORTS_RIMMINGTON, -1),
	STEEL_SALVAGING_HOOK("Steel salvaging hook", Rarity.COMMON, ItemID.SAILING_SKILLGUIDE_SALVAGING_HOOK_STEEL, -1),
	CATHERBY("Catherby", Rarity.UNCOMMON, ItemID.SAILING_SKILLGUIDE_PORTS_CATHERBY, -1),
	OAK_HULL("Oak hull", Rarity.UNCOMMON, ItemID.SAILING_SKILLGUIDE_OAK_HULL, -1),
	BRONZE_CANNON("Bronze cannon", Rarity.UNCOMMON, ItemID.SAILING_SKILLGUIDE_BRONZE_CANNON, -1),
	SEA_CURRENT_CHARTING("Sea current charting", Rarity.UNCOMMON, ItemID.SAILING_CHARTING_CURRENT_DUCK, -1),
	TEAK_HULL_HULL_PARTS("Teak hull & hull parts", Rarity.UNCOMMON, ItemID.SAILING_SKILLGUIDE_TEAK_HULL, -1),
	BRIMHAVEN("Brimhaven", Rarity.UNCOMMON, ItemID.SAILING_SKILLGUIDE_PORTS_BRIMHAVEN, -1),
	FLAGS("Flags", Rarity.UNCOMMON, ItemID.SAILING_SKILLGUIDE_FLAG_TEMPOR, -1),
	TRIMS("Trims", Rarity.UNCOMMON, ItemID.SAILING_SKILLGUIDE_BOAT_TRIM, -1),
	FISHERMAN_S_SHIPWRECKS("Fisherman's shipwrecks", Rarity.UNCOMMON, ItemID.SAILING_FISHERMAN_SHIPWRECK_SALVAGE, -1),
	TEAK_MAST_AND_CANVAS_SAILS("Teak mast and canvas sails", Rarity.UNCOMMON, ItemID.SAILING_SKILLGUIDE_MAST_TEAK, -1),
	ARDOUGNE("Ardougne", Rarity.UNCOMMON, ItemID.SAILING_SKILLGUIDE_PORTS_ARDOUGNE, -1),
	IRON_CANNON("Iron cannon", Rarity.UNCOMMON, ItemID.SAILING_SKILLGUIDE_IRON_CANNON, -1),
	ANCHOR("Anchor", Rarity.UNCOMMON, ItemID.SAILING_SKILLGUIDE_ANCHOR, -1),
	TEAK_CARGO_HOLD("Teak cargo hold", Rarity.UNCOMMON, ItemID.SAILING_SKILLGUIDE_BOAT_CARGO_HOLD_TEAK, -1),
	MITHRIL_SALVAGING_HOOK("Mithril salvaging hook", Rarity.UNCOMMON, ItemID.SAILING_SKILLGUIDE_SALVAGING_HOOK_MITHRIL, -1),
	PORT_KHAZARD("Port Khazard", Rarity.UNCOMMON, ItemID.SAILING_SKILLGUIDE_PORTS_PORT_KHAZARD, -1),
	THE_TEMPOR_TANTRUM_THE_STORM_TEMPOR("The Tempor Tantrum - The Storm Tempor", Rarity.UNCOMMON, ItemID.SAILING_SKILLGUIDE_FLAG_TEMPOR, -1),
	TEAK_HULL("Teak hull", Rarity.UNCOMMON, ItemID.SAILING_SKILLGUIDE_TEAK_HULL, -1),
	STEEL_KEEL("Steel keel", Rarity.UNCOMMON, ItemID.SAILING_SKILLGUIDE_KEEL_STEEL, -1),
	KEG("Keg", Rarity.UNCOMMON, ItemID.SAILING_SKILLGUIDE_KEG, -1),
	WITCHAVEN("Witchaven", Rarity.UNCOMMON, ItemID.SAILING_SKILLGUIDE_PORTS_WITCHAVEN, -1),
	BARRACUDA_SHIPWRECKS("Barracuda shipwrecks", Rarity.UNCOMMON, ItemID.SAILING_BARRACUDA_SHIPWRECK_SALVAGE, -1),
	ENTRANA("Entrana", Rarity.UNCOMMON, ItemID.SAILING_SKILLGUIDE_PORTS_ENTRANA, -1),
	CIVITAS_ILLA_FORTIS("Civitas illa Fortis", Rarity.UNCOMMON, ItemID.SAILING_SKILLGUIDE_PORTS_CIVITAS_ILLA_FORTIS, -1),
	SEA_DEPTH_CHARTING("Sea depth charting", Rarity.UNCOMMON, ItemID.HUNDRED_PIRATE_DIVING_HELMET, -1),
	STEEL_HELM("Steel helm", Rarity.UNCOMMON, ItemID.SAILING_SKILLGUIDE_HELM_STEEL, -1),
	STEEL_CANNON("Steel cannon", Rarity.UNCOMMON, ItemID.SAILING_SKILLGUIDE_STEEL_CANNON, -1),
	CORSAIR_COVE("Corsair Cove", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_PORTS_CORSAIR_COVE, -1),
	DOGNOSE_ISLAND("Dognose Island", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_OCEANS_UNQUIET, -1),
	INOCULATION_STATION("Inoculation station", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_FACILITY_INOCULATION_STATION, -1),
	JOBLESS_JIM_PORT_SARIM("Jobless Jim - Port Sarim", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_CREW_JOBLESS_JIM, -1),
	MAHOGANY_HULL_HULL_PARTS("Mahogany hull & hull parts", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_MAHOGANY_HULL, -1),
	CAIRN_ISLE("Cairn Isle", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_PORTS_CAIRN_ISLE, -1),
	CHINCHOMPA_ISLAND("Chinchompa Island", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_OCEANS_WESTERN, -1),
	SALVAGING_STATION("Salvaging station", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_SALVAGING_STATION, -1),
	SUNSET_COAST("Sunset Coast", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_PORTS_SUNSET_COAST, -1),
	MAHOGANY_MAST_AND_CANVAS_SAILS("Mahogany mast and canvas sails", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_MAST_MAHOGANY, -1),
	THE_LITTLE_PEARL("The Little Pearl", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_OCEANS_UNQUIET, -1),
	THE_SUMMER_SHORE("The Summer Shore", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_PORTS_THE_SUMMER_SHORE, -1),
	ALDARIN("Aldarin", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_PORTS_ALDARIN, -1),
	MAHOGANY_CARGO_HOLD("Mahogany cargo hold", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_BOAT_CARGO_HOLD_MAHOGANY, -1),
	VATRACHOS_ISLAND("Vatrachos Island", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_OCEANS_SHROUDED, -1),
	THE_ONYX_CREST("The Onyx Crest", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_OCEANS_UNQUIET, -1),
	MAHOGANY_HULL("Mahogany hull", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_MAHOGANY_HULL, -1),
	RUINS_OF_UNKAH("Ruins of Unkah", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_PORTS_RUINS_OF_UNKAH, -1),
	SHIMMERING_ATOLL("Shimmering Atoll", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_OCEANS_SUNSET, -1),
	BALLISTIC_ATTRACTOR("Ballistic attractor", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_BALLISTIC_ATTRACTOR, -1),
	CAPTAIN_SIAD_DESERT_MINING_CAMP("Captain Siad - Desert Mining Camp", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_CREW_CAPTAIN_SIAD, -1),
	MITHRIL_CANNON("Mithril cannon", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_MITHRIL_CANNON, -1),
	MITHRIL_KEEL("Mithril keel", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_KEEL_MITHRIL, -1),
	PORT_ROBERTS("Port Roberts", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_PORTS_PORT_ROBERTS, -1),
	SLOOP("Sloop", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_BOAT_HULL_KANDARIN_3X8_WOOD, -1),
	VOID_KNIGHTS_OUTPOST("Void Knights' Outpost", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_PORTS_VOID_KNIGHTS_OUTPOST, -1),
	ANGLERS_RETREAT("Anglers' Retreat", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_OCEANS_SHROUDED, -1),
	ADAMANT_SALVAGING_HOOK("Adamant salvaging hook", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_SALVAGING_HOOK_ADAMANT, -1),
	LARGE_SHIPWRECKS("Large shipwrecks", Rarity.RARE, ItemID.SAILING_LARGE_SHIPWRECK_SALVAGE, -1),
	WIND_CATCHER("Wind catcher", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_WIND_CATCHER, -1),
	MINOTAUR_S_REST("Minotaur's Rest", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_OCEANS_SHROUDED, -1),
	ADVENTURER_ADA_THE_PANDEMONIUM("Adventurer Ada - The Pandemonium", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_CREW_ADVENTURER_ADA, -1),
	ISLE_OF_SOULS("Isle of Souls", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_OCEANS_SHROUDED, -1),
	MITHRIL_HELM("Mithril helm", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_HELM_MITHRIL, -1),
	TELEPORT_FOCUS("Teleport focus", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_TELEPORTATION_FOCUS, -1),
	THE_JUBBLY_JIVE_BACKWATER("The Jubbly Jive - Backwater", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_FLAG_CHOMPY, -1),
	CHUM_STATION("Chum station", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_CHUM_STATION, -1),
	ISLE_OF_BONES("Isle of Bones", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_OCEANS_SHROUDED, -1),
	ROPE_TRAWLING_NET("Rope trawling net", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_ROPE_TRAWLING_NET, -1),
	WEATHER_PATTERN_CHARTING("Weather pattern charting", Rarity.RARE, ItemID.SAILING_CHARTING_WEATHER_STATION_EMPTY, -1),
	LAGUNA_AURORAE("Laguna Aurorae", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_OCEANS_SUNSET, -1),
	CAMPHOR_HULL_HULL_PARTS("Camphor hull & hull parts", Rarity.RARE, ItemID.SAILING_SKILLGUIDE_CAMPHOR_HULL, -1),
	CABIN_BOY_JENKINS_CRANDOR("Cabin Boy Jenkins - Crandor", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_CREW_CABIN_BOY_JENKINS, -1),
	CAMPHOR_CARGO_HOLD("Camphor cargo hold", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_BOAT_CARGO_HOLD_CAMPHOR, -1),
	CAMPHOR_MAST_AND_CANVAS_SAILS("Camphor mast and canvas sails", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_MAST_CAMPHOR, -1),
	CHARRED_ISLAND("Charred Island", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_OCEANS_UNQUIET, -1),
	ADAMANT_CANNON("Adamant cannon", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_ADAMANT_CANNON, -1),
	TEAR_OF_THE_SOUL("Tear of the Soul", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_OCEANS_SHROUDED, -1),
	ADAMANT_KEEL("Adamant keel", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_KEEL_ADAMANT, -1),
	RELLEKKA("Rellekka", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_PORTS_RELLEKKA, -1),
	WYRMSCRAIG("Wyrmscraig", Rarity.EPIC, 34058, -1),
	BOSUN_S_WORKBENCH("Bosun's workbench", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_BOSUNS_WORKBENCH, -1),
	WINTUMBER_ISLAND("Wintumber Island", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_OCEANS_SHROUDED, -1),
	PIRATE_SHIPWRECKS("Pirate shipwrecks", Rarity.EPIC, ItemID.SAILING_PIRATE_SHIPWRECK_SALVAGE, -1),
	THE_CROWN_JEWEL("The Crown Jewel", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_OCEANS_SHROUDED, -1),
	ETCETERIA("Etceteria", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_PORTS_ETCETERIA, -1),
	LINEN_TRAWLING_NET("Linen trawling net", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_LINEN_TRAWLING_NET, -1),
	OARSWOMAN_OLGA_BURGH_DE_ROTT("Oarswoman Olga - Burgh de Rott", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_CREW_OARSWOMAN_OLGA, -1),
	LLEDRITH_ISLAND("Lledrith Island", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_OCEANS_WESTERN, -1),
	PORT_TYRAS("Port Tyras", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_PORTS_PORT_TYRAS, -1),
	RUNE_SALVAGING_HOOK("Rune salvaging hook", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_SALVAGING_HOOK_RUNE, -1),
	CAMPHOR_HULL("Camphor hull", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_CAMPHOR_HULL, -1),
	DEEPFIN_POINT("Deepfin Point", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_PORTS_DEEPFIN_POINT, -1),
	ADVANCED_CHUM_STATION("Advanced chum station", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_CHUM_STATION_ADVANCED, -1),
	JATIZSO("Jatizso", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_PORTS_JATIZO, -1),
	NEITIZNOT("Neitiznot", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_PORTS_NEITIZNOT, -1),
	RAINBOW_S_END("Rainbow's End", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_OCEANS_SHROUDED, -1),
	FATHOM_STONE("Fathom stone", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_FATHOM_STONE, -1),
	JITTERY_JIM_PORT_KHAZARD("Jittery Jim - Port Khazard", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_CREW_JITTERY_JIM, -1),
	PRIFDDINAS("Prifddinas", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_PORTS_PRIFDDINAS, -1),
	ADAMANT_HELM("Adamant helm", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_HELM_ADAMANT, -1),
	SUNBLEAK_ISLAND("Sunbleak Island", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_OCEANS_SHROUDED, -1),
	THE_GWENITH_GLIDE_PORTH_GWENITH("The Gwenith Glide - Porth Gwenith", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_FLAG_GWEN, -1),
	CRYSTAL_EXTRACTOR("Crystal extractor", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_CRYSTAL_EXTRACTOR, -1),
	MERCENARY_SHIPWRECKS("Mercenary shipwrecks", Rarity.EPIC, ItemID.SAILING_MERCENARY_SHIPWRECK_SALVAGE, -1),
	YNYSDAIL("Ynysdail", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_OCEANS_WESTERN, -1),
	WATERBIRTH_ISLAND("Waterbirth Island", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_OCEANS_NORTHERN, -1),
	GREATER_TELEPORT_FOCUS("Greater teleport focus", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_TELEPORTATION_FOCUS_GREATER, -1),
	IRONWOOD_HULL_HULL_PARTS("Ironwood hull & hull parts", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_IRONWOOD_HULL, -1),
	PISCATORIS("Piscatoris", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_PORTS_PISCATORIS, -1),
	BUCCANEERS_HAVEN("Buccaneers' Haven", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_OCEANS_WESTERN, -1),
	HEMP_TRAWLING_NET("Hemp trawling net", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_HEMP_TRAWLING_NET, -1),
	LUNAR_ISLE("Lunar Isle", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_PORTS_LUNAR_ISLE, -1),
	RUNE_CANNON("Rune cannon", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_RUNE_CANNON, -1),
	IRONWOOD_MAST_AND_COTTON_SAILS("Ironwood mast and cotton sails", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_MAST_IRONWOOD, -1),
	DRAGON_SALVAGING_HOOK("Dragon salvaging hook", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_SALVAGING_HOOK_DRAGON, -1),
	ETERNAL_BRAZIER("Eternal brazier", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_BOAT_ETERNAL_BRAZIER, -1),
	RUNE_KEEL("Rune keel", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_KEEL_RUNE, -1),
	DRUMSTICK_ISLE("Drumstick Isle", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_OCEANS_WESTERN, -1),
	GALE_CATCHER("Gale catcher", Rarity.EPIC, ItemID.SAILING_SKILLGUIDE_GALE_CATCHER, -1),
	BOSUN_ZARAH_ETCETERIA("Bosun Zarah - Etceteria", Rarity.LEGENDARY, ItemID.SAILING_SKILLGUIDE_CREW_BOSUN_ZARAH, -1),
	FREMENNIK_SHIPWRECKS("Fremennik shipwrecks", Rarity.LEGENDARY, ItemID.SAILING_FREMENNIK_SHIPWRECK_SALVAGE, -1),
	IRONWOOD_CARGO_HOLD("Ironwood cargo hold", Rarity.LEGENDARY, ItemID.SAILING_SKILLGUIDE_BOAT_CARGO_HOLD_IRONWOOD, -1),
	WEISS("Weiss", Rarity.LEGENDARY, ItemID.SAILING_SKILLGUIDE_OCEANS_NORTHERN, -1),
	BRITTLE_ISLE("Brittle Isle", Rarity.LEGENDARY, ItemID.SAILING_SKILLGUIDE_OCEANS_NORTHERN, -1),
	IRONWOOD_HULL("Ironwood hull", Rarity.LEGENDARY, ItemID.SAILING_SKILLGUIDE_IRONWOOD_HULL, -1),
	CHUM_SPREADER("Chum spreader", Rarity.LEGENDARY, ItemID.SAILING_SKILLGUIDE_CHUM_SPREADER, -1),
	COTTON_TRAWLING_NET("Cotton trawling net", Rarity.LEGENDARY, ItemID.SAILING_SKILLGUIDE_COTTON_TRAWLING_NET, -1),
	DRAGON_CANNON("Dragon cannon", Rarity.LEGENDARY, ItemID.SAILING_SKILLGUIDE_DRAGON_CANNON, -1),
	ROSEWOOD_HULL_HULL_PARTS("Rosewood hull & hull parts", Rarity.LEGENDARY, ItemID.SAILING_SKILLGUIDE_ROSEWOOD_HULL, -1),
	JOLLY_JIM_BRIMHAVEN("Jolly Jim - Brimhaven", Rarity.LEGENDARY, ItemID.SAILING_SKILLGUIDE_CREW_JOLLY_JIM, -1),
	ROSEWOOD_MAST_AND_COTTON_SAILS("Rosewood mast and cotton sails", Rarity.LEGENDARY, ItemID.SAILING_SKILLGUIDE_MAST_ROSEWOOD, -1),
	DRAGON_KEEL("Dragon keel", Rarity.LEGENDARY, ItemID.SAILING_SKILLGUIDE_KEEL_DRAGON, -1),
	GRIMSTONE("Grimstone", Rarity.LEGENDARY, ItemID.SAILING_SKILLGUIDE_OCEANS_NORTHERN, -1),
	MERCHANT_SHIPWRECKS("Merchant shipwrecks", Rarity.LEGENDARY, ItemID.SAILING_MERCHANT_SHIPWRECK_SALVAGE, -1),
	RUNE_HELM("Rune helm", Rarity.LEGENDARY, ItemID.SAILING_SKILLGUIDE_HELM_RUNE, -1),
	ROSEWOOD_CARGO_HOLD("Rosewood cargo hold", Rarity.LEGENDARY, ItemID.SAILING_SKILLGUIDE_BOAT_CARGO_HOLD_ROSEWOOD, -1),
	SPOTTER_VIRGINIA_RUINS_OF_UNKAH("Spotter Virginia - Ruins of Unkah", Rarity.LEGENDARY, ItemID.SAILING_SKILLGUIDE_CREW_SPOTTER_VIRGINIA, -1),
	FATHOM_PEARL("Fathom pearl", Rarity.LEGENDARY, ItemID.SAILING_SKILLGUIDE_FATHOM_PEARL, -1),
	ROSEWOOD_HULL("Rosewood hull", Rarity.LEGENDARY, ItemID.SAILING_SKILLGUIDE_ROSEWOOD_HULL, -1),
	SAILOR_JAKOB_CATHERBY("Sailor Jakob - Catherby", Rarity.LEGENDARY, ItemID.SAILING_SKILLGUIDE_CREW_SAILOR_JAKOB, -1),
	DRAGON_HELM("Dragon helm", Rarity.LEGENDARY, ItemID.SAILING_SKILLGUIDE_HELM_DRAGON, -1),
	SKILLCAPE("Skillcape", Rarity.LEGENDARY, ItemID.SKILLCAPE_SAILING, -1);

	private final Card card;

	SailingCards(String name, Rarity rarity, int itemId, int spriteId)
	{
		this.card = CardGroup.build(CardSet.SAILING, name, rarity, itemId, spriteId);
	}

	@Override
	public Card getCard()
	{
		return card;
	}
}
